In [3]:
import array as arr
my_array=arr.array('i',[1,2,3,4,5])
print(my_array)
print(my_array[0])

array('i', [1, 2, 3, 4, 5])
1


In [4]:
my_array.append(6)
print(my_array)

array('i', [1, 2, 3, 4, 5, 6])


In [8]:
import numpy as np
numpy_array=np.array([1,2,3,4])
print(numpy_array)
print(numpy_array*2)
multi_dim_array=np.array([[1,2],[3,4]])
print(multi_dim_array)

[1 2 3 4]
[2 4 6 8]
[[1 2]
 [3 4]]


In [6]:
import array as arr
my_array=arr.array('I',[1,2,3,4,5])
print(my_array)
print(my_array[0])

array('I', [1, 2, 3, 4, 5])
1


In [7]:
import array as arr
my_array=arr.array('I',[-1,-2,-3,-4,-5])
print(my_array)
print(my_array[0])

OverflowError: can't convert negative value to unsigned int

In [9]:
import random
arr=[1,2,3,4]
print(random.choice(arr))

1


In [10]:
import random
friends=["Alice","Bob","Charlie","David"]
print(random.choice(friends))

Bob


In [33]:
import friends
import random
random.choice( friends.name)

'keerthana'

In [7]:
import random
friends=["Alice","Bob","Charlie","David"]
random_index=random.randint(0,4)
print(friends[random_index])

Charlie


In [9]:
fruits=["apple","banana","graps","mango","pine apple"]
vegetables=["spinach","tomatos","kale","celery","potatoes"]
dirty_dozen=[fruits,vegetables]
print(dirty_dozen[0][4])

pine apple


In [15]:
import random
my_list=['apple','banana','cherry','date','date']
# select a single random element
random_item=random.choice(my_list)
print(f"random_item:{random_item}")

random_item:cherry


In [21]:
#select 3 unique random elements(without replacement)
random_sample_unique=random.sample(my_list,4)
print(random_sample_unique)

['cherry', 'banana', 'apple', 'date']


In [13]:
print(dirty_dozen[int(input())][int(input())])

 1
 3


celery


In [33]:
dirty_dozen=[fruits,vegetables]
index1=int(input())
index2=int(input())
if(0<=index1<len(dirty_dozen)):
    if(index2<len(fruits) and index1==0):
        print(dirty_dozen[index1][index2])
    elif(index1<len(vegetables)and(index1==1)):
        print(dirty_dozen[index1][index2])
    else:
        print("out of index")
else:
    print("out of index")

 3
 3


out of index


In [38]:
for fruit in fruits:
    print(fruit)
    print(fruit+"pie")
    print(f"{fruit}pie")

apple
applepie
applepie
banana
bananapie
bananapie
graps
grapspie
grapspie
mango
mangopie
mangopie
pine apple
pine applepie
pine applepie


In [42]:
for index in dirty_dozen:
    for fruit in dirty_dozen[0]:
        print(fruit)
        print(fruit+ "pie")

apple
applepie
banana
bananapie
graps
grapspie
mango
mangopie
pine apple
pine applepie
apple
applepie
banana
bananapie
graps
grapspie
mango
mangopie
pine apple
pine applepie


In [44]:
for index in range(0,len( dirty_dozen)):
    for fruit in dirty_dozen[0]:
        print(fruit)
        print(fruit+ "pie")  

apple
applepie
banana
bananapie
graps
grapspie
mango
mangopie
pine apple
pine applepie
apple
applepie
banana
bananapie
graps
grapspie
mango
mangopie
pine apple
pine applepie


In [45]:
my_list=[1,2,3,4,5]
for element in my_list:
    print(element)
    if(element==4):
        break
    else:
        continue
        print(element)

1
2
3
4


In [48]:
my_list=[1,2,3,4,5]
for element in my_list:
    if(element==4):
        break
    else:
        pass
        print(element)

1
2
3


In [54]:

my_word="listen"
for c in my_word:
    charlist=[]
    print(c)
    charlist.append(c)

l
i
s
t
e
n


In [55]:
my_word="listen"
l=[]
for c in my_word:
    print(c)
    l.append(c)
l.sort()


l
i
s
t
e
n


In [56]:
l

['e', 'i', 'l', 'n', 's', 't']