In [1]:
import pandas as pd
df = pd.read_csv('car.csv')
print(df.to_string())    

                      Car_Name  Year  Selling_Price  Present_Price  Kms_Driven Fuel_Type Seller_Type Transmission  Owner
0                         ritz  2014           3.35          5.590       27000    Petrol      Dealer       Manual      0
1                          sx4  2013           4.75          9.540       43000    Diesel      Dealer       Manual      0
2                         ciaz  2017           7.25          9.850        6900    Petrol      Dealer       Manual      0
3                      wagon r  2011           2.85          4.150        5200    Petrol      Dealer       Manual      0
4                        swift  2014           4.60          6.870       42450    Diesel      Dealer       Manual      0
5                vitara brezza  2018           9.25          9.830        2071    Diesel      Dealer       Manual      0
6                         ciaz  2015           6.75          8.120       18796    Petrol      Dealer       Manual      0
7                      s cross  

In [6]:
print(pd.options.display.max_columns)

20


In [2]:
df1=df.sample(n=10,random_state=1)

In [13]:
pd.options.display.max_rows = 4999
print(df)

                      Car_Name  Year  Selling_Price  Present_Price  \
0                         ritz  2014           3.35          5.590   
1                          sx4  2013           4.75          9.540   
2                         ciaz  2017           7.25          9.850   
3                      wagon r  2011           2.85          4.150   
4                        swift  2014           4.60          6.870   
5                vitara brezza  2018           9.25          9.830   
6                         ciaz  2015           6.75          8.120   
7                      s cross  2015           6.50          8.610   
8                         ciaz  2016           8.75          8.890   
9                         ciaz  2015           7.45          8.920   
10                    alto 800  2017           2.85          3.600   
11                        ciaz  2015           6.85         10.380   
12                        ciaz  2015           7.50          9.940   
13                  

In [6]:
dif1['datesPurchased']=dates
print(dif1.to_string()) 

    Car_Name  Year  Selling_Price  Present_Price  Kms_Driven Fuel_Type Seller_Type Transmission  Owner datesPurchased
285     jazz  2016            7.4            8.5       15059    Petrol      Dealer    Automatic      0     02-03-2024
248      i10  2013            4.0            4.6       30000    Petrol      Dealer       Manual      0     04-09-2025


In [ ]:
df1.to_excel('output.xlxs')

In [7]:
dates=["02-03-2024","04-09-2025"]
dif1=df.sample(n=2,random_state=1)
dif1['datesPurchased']=dates
print(dif1.to_string())

    Car_Name  Year  Selling_Price  Present_Price  Kms_Driven Fuel_Type Seller_Type Transmission  Owner datesPurchased
285     jazz  2016            7.4            8.5       15059    Petrol      Dealer    Automatic      0     02-03-2024
248      i10  2013            4.0            4.6       30000    Petrol      Dealer       Manual      0     04-09-2025


In [18]:
df1.to_excel('output.xlsx')

In [19]:
pd.read_excel('output.xlsx')

Unnamed: 0                   Car_Name  Year  Selling_Price  Present_Price  \
0         285                       jazz  2016           7.40          8.500   
1         248                        i10  2013           4.00          4.600   
2         150         TVS Apache RTR 180  2011           0.50          0.826   
3         217                        eon  2016           3.15          4.430   
4         107  Royal Enfield Thunder 350  2013           1.25          1.500   
5         206                      xcent  2017           5.75          7.130   
6         132          Bajaj Avenger 220  2017           0.75          0.950   
7          73                 etios liva  2011           2.65          5.710   
8         288                       city  2015           8.40         13.600   
9         157          Yamaha FZ S V 2.0  2015           0.48          0.840   

   Kms_Driven Fuel_Type Seller_Type Transmission  Owner  
0       15059    Petrol      Dealer    Automatic      0  
1       30000    Petrol      Dealer       Manual      0  
2        6000    Petrol  Individual       Manual      0  
3       15000    Petrol      Dealer       Manual      0  
4       15000    Petrol  Individual       Manual      0  
5       12479    Petrol      Dealer       Manual      0  
6        3500    Petrol  Individual       Manual      0  
7       43000    Petrol      Dealer       Manual      0  
8       34000    Petrol      Dealer       Manual      0  
9       23000    Petrol  Individual       Manual      0

In [34]:
parseDate = pd.read_excel("out3.xlsx")
parseDate['joinDates'] = pd.to_datetime(parseDate['joinDates'], dayfirst=True)
parseDate

Unnamed: 0 Car_Name  Year  Selling_Price  Present_Price  Kms_Driven  \
0         285     jazz  2016            7.4            8.5       15059   
1         248      i10  2013            4.0            4.6       30000   

  Fuel_Type Seller_Type Transmission  Owner company  joinDates  
0    Petrol      Dealer    Automatic      0     abc 2024-05-21  
1    Petrol      Dealer       Manual      0     xyz 2023-03-23

In [26]:
name = ["abc","xyz"]
dates = ["21-05-2024","23-03-2023"]
dif2 = df.sample(n=2, random_state=1)
dif2["company"]=name
dif2["joinDates"]=dates
print(dif2.to_string())

    Car_Name  Year  Selling_Price  Present_Price  Kms_Driven Fuel_Type Seller_Type Transmission  Owner company   joinDates
285     jazz  2016            7.4            8.5       15059    Petrol      Dealer    Automatic      0     abc  21-05-2024
248      i10  2013            4.0            4.6       30000    Petrol      Dealer       Manual      0     xyz  23-03-2023


In [27]:
dif2.to_excel('out3.xlsx')

In [28]:
pd.read_excel('out3.xlsx')

Unnamed: 0 Car_Name  Year  Selling_Price  Present_Price  Kms_Driven  \
0         285     jazz  2016            7.4            8.5       15059   
1         248      i10  2013            4.0            4.6       30000   

  Fuel_Type Seller_Type Transmission  Owner company   joinDates  
0    Petrol      Dealer    Automatic      0     abc  21-05-2024  
1    Petrol      Dealer       Manual      0     xyz  23-03-2023

In [36]:
data = {
    "calories":[230,120,350],
    "duration":[10,30,50]
}
df = pd.DataFrame(data)
print(df)

   calories  duration
0       230        10
1       120        30
2       350        50


In [37]:
print(df.iloc[0:1,0:1])

   calories
0       230


In [41]:
print(df.loc[[0,1]])

   calories  duration
0       230        10
1       120        30


In [ ]:
df.to_excel("")

In [1]:
import numpy as np
a=np.array([[1,2,3],[0,9,8]])
print(a)

[[1 2 3]
 [0 9 8]]


In [7]:
b=np.array(5)
c=np.array([1,2,3,4,])
d=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(d.ndim)

3


In [10]:
np.full?

Signature:
np.full(
    shape,
    fill_value,
    dtype=None,
    order='C',
    *,
    device=None,
    like=None,
)
Docstring:
Return a new array of given shape and type, filled with `fill_value`.

Parameters
----------
shape : int or sequence of ints
    Shape of the new array, e.g., ``(2, 3)`` or ``2``.
fill_value : scalar or array_like
    Fill value.
dtype : data-type, optional
    The desired data-type for the array  The default, None, means
     ``np.array(fill_value).dtype``.
order : {'C', 'F'}, optional
    Whether to store multidimensional data in C- or Fortran-contiguous
    (row- or column-wise) order in memory.
device : str, optional
    The device on which to place the created array. Default: None.
    For Array-API interoperability only, so must be ``"cpu"`` if passed.

    .. versionadded:: 2.0.0
like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
     

In [21]:
a=np.array([[1,2,3,5,7],[8,4,2,6,1]])
print(a[0:2,1:])
print(a.reshape)

[[2 3 5 7]
 [4 2 6 1]]
<built-in method reshape of numpy.ndarray object at 0x000001EC239978D0>


In [26]:
a=np.array([1,2,3,5,7,8,4,2,6,1])
newa= np.reshape(a,(5,2))
print(newa)

[[1 2]
 [3 5]
 [7 8]
 [4 2]
 [6 1]]


In [28]:
a=np.array([1,2,3,5,7,8,4,2,6,1,5,3])
newa=np.reshape(a,(2,2,-1))
print(newa)

[[[1 2 3]
  [5 7 8]]

 [[4 2 6]
  [1 5 3]]]


In [30]:
a=np.array([1,2,3,5,7,8,4,2,6,1,5,3])
newa=np.reshape(a,(2,2,3))
print(newa)

[[[1 2 3]
  [5 7 8]]

 [[4 2 6]
  [1 5 3]]]


In [37]:
a=np.array([1,2,3,5,7,8,4,2,6,1,5,3])
newa=np.reshape(a,(2,3,-1))
c=newa.base
print(newa)
c

[[[1 2]
  [3 5]
  [7 8]]

 [[4 2]
  [6 1]
  [5 3]]]


array([1, 2, 3, 5, 7, 8, 4, 2, 6, 1, 5, 3])

In [38]:
c=np.array([[1,2,3,5,7,12],[8,4,2,6,1,23]])
newc=c.reshape(-1)
print(newc)

[ 1  2  3  5  7 12  8  4  2  6  1 23]


In [41]:
a=round(-236.4)
print(a)

-236


In [45]:
marks=np.array([77,78,85,86,86,86,87,87,94,98,99,103])
print(np.mean(marks))
print(np.median(marks))

88.83333333333333
86.5


In [47]:
from scipy import stats
print(stats.mode(marks))

ModeResult(mode=np.int64(86), count=np.int64(3))
