In [5]:
import pandas as pd 
df = pd.read_csv('car.csv')
print(df.to_string())

                      Car_Name  Year  Selling_Price  Present_Price  Kms_Driven Fuel_Type Seller_Type Transmission  Owner
0                         ritz  2014           3.35          5.590       27000    Petrol      Dealer       Manual      0
1                          sx4  2013           4.75          9.540       43000    Diesel      Dealer       Manual      0
2                         ciaz  2017           7.25          9.850        6900    Petrol      Dealer       Manual      0
3                      wagon r  2011           2.85          4.150        5200    Petrol      Dealer       Manual      0
4                        swift  2014           4.60          6.870       42450    Diesel      Dealer       Manual      0
5                vitara brezza  2018           9.25          9.830        2071    Diesel      Dealer       Manual      0
6                         ciaz  2015           6.75          8.120       18796    Petrol      Dealer       Manual      0
7                      s cross  

In [6]:
import pandas as pd
print(pd.options.display.max_rows)

60


In [7]:
pd.options.display.max_rows=9999
print(df)

                      Car_Name  Year  Selling_Price  Present_Price  \
0                         ritz  2014           3.35          5.590   
1                          sx4  2013           4.75          9.540   
2                         ciaz  2017           7.25          9.850   
3                      wagon r  2011           2.85          4.150   
4                        swift  2014           4.60          6.870   
5                vitara brezza  2018           9.25          9.830   
6                         ciaz  2015           6.75          8.120   
7                      s cross  2015           6.50          8.610   
8                         ciaz  2016           8.75          8.890   
9                         ciaz  2015           7.45          8.920   
10                    alto 800  2017           2.85          3.600   
11                        ciaz  2015           6.85         10.380   
12                        ciaz  2015           7.50          9.940   
13                  

In [55]:
df1 = df.sample(n=10,random_state=1)

In [38]:
df1.to_excel('car.xlsx')

In [30]:
pd.read_excel("dupcar.xlsx")

Unnamed: 0                   Car_Name  Year  Selling_Price  Present_Price  \
0         285                       jazz  2016           7.40          8.500   
1         248                        i10  2013           4.00          4.600   
2         150         TVS Apache RTR 180  2011           0.50          0.826   
3         217                        eon  2016           3.15          4.430   
4         107  Royal Enfield Thunder 350  2013           1.25          1.500   
5         206                      xcent  2017           5.75          7.130   
6         132          Bajaj Avenger 220  2017           0.75          0.950   
7          73                 etios liva  2011           2.65          5.710   
8         288                       city  2015           8.40         13.600   
9         157          Yamaha FZ S V 2.0  2015           0.48          0.840   

   Kms_Driven Fuel_Type Seller_Type Transmission  Owner  
0       15059    Petrol      Dealer    Automatic      0  
1       30000    Petrol      Dealer       Manual      0  
2        6000    Petrol  Individual       Manual      0  
3       15000    Petrol      Dealer       Manual      0  
4       15000    Petrol  Individual       Manual      0  
5       12479    Petrol      Dealer       Manual      0  
6        3500    Petrol  Individual       Manual      0  
7       43000    Petrol      Dealer       Manual      0  
8       34000    Petrol      Dealer       Manual      0  
9       23000    Petrol  Individual       Manual      0

In [56]:
dates=["10-06-2001","12-10-2002"]
print(pd.read_excel("dupcar.xlsx"))

   Unnamed: 0                   Car_Name  Year  Selling_Price  Present_Price  \
0         285                       jazz  2016           7.40          8.500   
1         248                        i10  2013           4.00          4.600   
2         150         TVS Apache RTR 180  2011           0.50          0.826   
3         217                        eon  2016           3.15          4.430   
4         107  Royal Enfield Thunder 350  2013           1.25          1.500   
5         206                      xcent  2017           5.75          7.130   
6         132          Bajaj Avenger 220  2017           0.75          0.950   
7          73                 etios liva  2011           2.65          5.710   
8         288                       city  2015           8.40         13.600   
9         157          Yamaha FZ S V 2.0  2015           0.48          0.840   

   Kms_Driven Fuel_Type Seller_Type Transmission  Owner  
0       15059    Petrol      Dealer    Automatic      0  
1  

In [58]:
newdf = pd.read_excel("dupcar.xlsx",parse_dates=[10])

IndexError: list index out of range (sheet: 0)

In [63]:
import pandas
data={
    "calories":[420,242,534],
    "duration":[50,40,30]
}
df = pd.DataFrame(data)
print(df)

   calories  duration
0       420        50
1       242        40
2       534        30


In [81]:
print(df.iloc[0,1])

50


In [82]:
print(df.loc[[0,1]])

   calories  duration
0       420        50
1       242        40


In [84]:
df.to_json(orient='split')

'{"columns":["calories","duration"],"index":[0,1,2],"data":[[420,50],[242,40],[534,30]]}'

In [86]:
import pandas as pd
pd.read_json(StringIO(_),orient='split')

NameError: name 'StringIO' is not defined

In [ ]:
arr = np.array(42) which is called 0 dimentional array because it contains one value

In [ ]:
arr=np.array([1,2,3])  its a one dimentional

In [88]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [100]:
a=np.array(42)
b=np.array([1,2,3,4,5,6])
c=np.array([[1,2,3,4],[5,6,7,8]])
d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[4,5,6]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [97]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,4])

10


In [110]:
print(c[0:2,2])

[3 7]


In [101]:
print(arr[-1,-1])

10


In [104]:

np.full((2,2),[10])

array([[10, 10],
       [10, 10]])

In [108]:
import numpy as np

np.inf(2,2)

TypeError: 'float' object is not callable

In [109]:
b[-3:-1]

array([4, 5])

In [132]:
arr=np.array([1,2,3,4,5])
x=arr
x[0]=54
print(arr)
print(x)

[54  2  3  4  5]
[54  2  3  4  5]


In [130]:
arr=np.array([1,2,3,4,5])
x=arr.copy()
x[0]=54
print(arr)
print(x)

[1 2 3 4 5]
[54  2  3  4  5]


In [115]:
print(b.shape)

(6,)


In [125]:
brr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr= brr.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [121]:
newarr.ndim

2

In [123]:
brr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newbrr= brr.reshape(2,3,2)
print(newbrr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [137]:
crr=np.array([1,2,3,4,5,6,7,8])
print(crr.reshape(2,2,-1))


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [142]:
crr=np.array([1,2,3,4,5,6,7,8])
print(crr.reshape(1,-1,2))


[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


In [145]:
drr=np.array([1,2,3,4,5,6,7,8])
drr[0]=10
print(drr.reshape(2,4).base)


[10  2  3  4  5  6  7  8]


In [146]:
d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[4,5,6]]])
print(d.reshape(-1))

[1 2 3 4 5 6 7 8 9 4 5 6]


In [149]:
mean=(99+86+87+87+88+86+86+77+78+85+88+94+103+111)/13
print(round(mean))

97


In [158]:
 
a=[85, 86, 86, 87, 87, 88, 88, 94]
sum=0
count=0
for i in a:
    sum += i
    count += 1
print(f"mean {sum/count}")
print()

mean 87.625



In [178]:
import numpy
a=[85, 86, 86, 87, 87, 88, 88, 94]
x=numpy.mean(a)
print(x)

87.625


In [179]:
from scipy import stats
x=stats.mode(a)
print(x)

ModeResult(mode=np.int64(86), count=np.int64(2))


In [180]:
65*65

4225

In [181]:
30*25

750

In [182]:
105.75/7


15.107142857142858