In [1]:
## loops and list


In [9]:
import array as arr
my_arr = arr.array('i',[1,2,3,4,600])
print (my_arr)

array('i', [1, 2, 3, 4, 600])


In [7]:
print(my_arr[])

1


In [11]:
my_arr.append(7)
print(my_arr)

array('i', [1, 2, 3, 4, 5, 6])


In [52]:
import array as arr
my_arr = arr.array('b',[127])
print (my_arr)

array('b', [127])


In [54]:
import numpy as np
my_num = np.array([1,2,3,4,5])
print(my_num)

[1 2 3 4 5]


In [55]:
print(my_num * 2)

[ 2  4  6  8 10]


In [58]:
my_2d = np.array([[1,2],[3,4]])
print(my_2d)

[[1 2]
 [3 4]]


In [68]:
import random
list = ["karthik","hari","durga","chandra","ganeshan"]
print(random.choice(list))

ganeshan


In [72]:
print(random.choice(my_arr))

3


In [4]:
import sample as sam
import random
print(random.choice(sam.list_name))

56789


In [3]:
from example import sample,test
import random
print(random.choice(sample.list_name))
print(random.choice(test.my_var))

c657
friends


In [24]:
import random
my_check = ["alice","rob","charlie","david","eve"] 
ran_inx = random.randint(0,4)
print(my_check[ran_inx])

eve


In [26]:
fruits = ["strawberries","nectraines""apples","grapes","peaches","cherries"]
veggies = ["spinach","kale","tomatoes","celery","potatoes"]
dirty_dozen = [fruits,veggies]
type(dirty_dozen)

list

In [35]:
print(dirty_dozen)

[['strawberries', 'nectraines', 'apples', 'grapes', 'peaches', 'cherries'], ['spinach', 'kale', 'tomatoes', 'celery', 'potatoes']]


In [36]:
print(dirty_dozen[1][2])

tomatoes


In [38]:
my_list = ['apple','banana','cherry','date','elderberry']
rand_item = random.choice(my_list)

print(f"Random item: {rand_item}")

Random item: date


In [50]:
fruits = ["strawberries","apples","grapes","peaches","cherries"]
veggies = ["spinach","kale","tomatoes","celery","potatoes","DrumSticks"]
dirty_dozen = [fruits,veggies]
index_1 = int(input())
index_2 = int(input())
if(0 <= index_1 < len(dirty_dozen)):
    if(0<= index_2 < len(veggies) and index_1 == 1):
        print(dirty_dozen[index_1][index_2])
    elif(0<= index_2 < len(fruits) and index_1 == 0):
        print(dirty_dozen[index_1][index_2])
    else:
        print("Invalid Values")
else:
    
    print("enter the valid index")


 0
 2


grapes


In [54]:
for fruit in fruits:
    print(fruit)
    print(f"{fruit}" "pie")

strawberries
strawberriespie
apples
applespie
grapes
grapespie
peaches
peachespie
cherries
cherriespie


In [5]:
index_1 = int(input())
index_2 = int(input())
for index_1 in (0,len(dirty_dozen)):
    if(0<= index_2 <len(fruits)):
        print(dirty_dozen[index_1][index_2])
    else:
        print("out of bountry")
else:
    print("out of bountry")

 1
 0


NameError: name 'dirty_dozen' is not defined

In [60]:
count =input("how many numbers do you want to sum:")
sum =0
marks= []
v=0
if(count.isdigit()):
    count = int(count)
    for i in range(0,count):
        val = input("enter the number")
        if(val.isdigit()):
            val = int(val)
            marks.append(val)
            v +=1
        else:
            print("enter number only")
            break 
else:
    print("enter number only")
    print("hiii")


if(v==count):
    print("your sum is ",sumMarks(marks))
    
def sumMarks(x):
    sum =0
    for i in x:
        sum +=i

    return(sum)


    

 

how many numbers do you want to sum: fefs


enter number only
hiii


In [61]:
for i in range(1,21):
    if(i%3==0 and i%5==0):
        print("fizzbuzz")
    elif(i%3==0):
        print("fizz")
    elif(i%5==0):
        print("buzz") 
    else:
        print(i)

1
2
fizz
4
buzz
fizz
7
8
fizz
buzz
11
fizz
13
14
fizzbuzz
16
17
fizz
19
buzz


In [43]:
weight= input("enter your weight:")
height= input("enter your height:")
if((weight.replace('.',"").isdigit()) and (height.replace('.',"").isdigit())):
    weight = float(weight)
    height = float(height)
    bmi = weight / (height ** 2)

    if(bmi>=30):
        print(bmi)
        print("obese")
    elif(25 <= bmi <30):
        print(bmi)
        print("overweight")
    elif(18.5 <= bmi < 25):
        print(bmi)
        print("normal")
    else:
        print(bmi)
        print("underweight")
else:
    print("enter number only")

enter your weight: 10
enter your height: 1


TypeError: unsupported operand type(s) for ** or pow(): 'str' and 'int'

In [44]:
string1=input("enter the first string").strip()
string2=input("enter the second string").strip()
count=0
if(len(string1) == len(string2) and string1.isalpha() and string2.isalpha()):
    for i in range (0,len(string1)):
        a=string1[i]
        for j in range(0,len(string2)):
            b = string2[j]
            if(a == b):
                count +=1
                string3=string2.replace(string2[j]," ")
                
            j +=1
        string2=string3
        i +=1

    if(count == len(string1)):
        print("anagram")
    else:
        print("not an anagram")
else:
    print("two string length should be same")
            

enter the first string 12bi
enter the second string bi21


two string length should be same


In [38]:
pwd = input("enter your password: ").strip()
list_chr = ['!', '@', '#', '$', '%', '^', '&', '*', '(', ')','-', '_', '+', '=', ':', ';' ]
def spl_ch(x):
    count =0 
    for i in range(0,len(x)):
        y=x[i]
        if(y in list_chr):
            count +=1;
        
    return count

def num(x):
    count = 0
    for i in range(0,len(x)):
        y= x[i]
        if(y.isdigit()):
            if(y.isdigit()):
                count+=1
    
    return count


def low(x):
    count =0 
    for i in range(0,len(x)):
        y=x[i]
        z=y
        if(x.isalpha()):
            if(z == y.lower()):
                count +=1
    return count

def high(x):
    count =0 
    for i in range(0,len(x)):
        y=x[i]
        z=y
        if(x.isalpha()):
            if(z == y.upper()):
                count +=1

    return count



if(len(pwd)>=8):
    if(spl_ch(pwd) >= 2):
        if((num(pwd) >= 1)):
            if((low(pwd) >=1) and (high(pwd) >= 1)):
                if(2 < spl_ch(pwd) <=4):
                    print("strong password")
                elif(spl_ch(pwd) > 4):
                    print("very strong password")
                else:
                    print("valid password")
            else:
                print("it should be one lower and upper case")
        else:
                print("invalid password")
    else:
        print("special character atleast two ")
else:
    print("password length should be more then 8 character")
    

enter your password:  rfgb


password length should be more then 8 character


In [73]:
str="karthik"
char_list = []
for c in str:
    char_list.append(c)
    print(c)
    
list1=char_list
print(list1)
char_list.sort()
print(char_list)

k
a
r
t
h
i
k
['k', 'a', 'r', 't', 'h', 'i', 'k']
['a', 'h', 'i', 'k', 'k', 'r', 't']


In [74]:
var="xcelevate"
sort_var=sorted(var)
print(sort_var)

['a', 'c', 'e', 'e', 'e', 'l', 't', 'v', 'x']
