In [6]:
import array as arr
array1=arr.array('b',[1,2,3,4,5])
print(array1)
print(array1[0])
array1.append(6)
print(array1)


array('b', [1, 2, 3, 4, 5])
1
array('b', [1, 2, 3, 4, 5, 6])


In [8]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a)
print(a*2)
print(a+2)
print(a-2)
md=np.array([[1,2],[3,4]])
print(md)
print(md.shape)
print(md.dtype)
print (type((type(md))))

[1 2 3 4 5]
[ 2  4  6  8 10]
[3 4 5 6 7]
[-1  0  1  2  3]
[[1 2]
 [3 4]]
(2, 2)
int64
<class 'type'>


In [2]:
import numpy


In [4]:
import random
import day2_module

In [5]:
friends=["moorthi","mani","aathif","vicky"]

In [9]:
print(random.choice(day2_module.friends),random.choice(friends))

moorthi mani


In [8]:
from python_folder import day2_module
print(random.choice(day2_module.friends))

moorthi


In [17]:
friends=["moorthi","mani","aathif","vicky"]
index_value=random.randint(0,4)
print(friends[index_value])

mani


In [27]:
fruit=["apple","orange","mango"]
veg=["potato","tomato","onion"]
dirty_dozen=[fruit,veg]
type(dirty_dozen)
print(dirty_dozen[1][1],dirty_dozen[1][2])


tomato onion


In [12]:
import random
my_list=['apple','banana','cherry','date','elderberry']
random_item=random.choice(my_list)
print(f"random item :{random_item}")
sample_unique=random.sample(my_list,3)
print(f"random sample(unique):{sample_unique}")


random item :apple
random sample(unique):['apple', 'banana', 'elderberry']


In [11]:
import random
fruit=["apple","orange","mango"]
veg=["potato","tomato","onion","bringe"]
dirty_dozen=[fruit,veg]
index1=int(input("index1"))
index2=int(input("index2"))
if(0<=index1<len(dirty_dozen)):
    if(index2<len(veg) and index1==0):
        print(dirty_dozen[index1][index2])
    elif(0<index2<len(veg) and index1==1):
        print(dirty_dozen[index1][index2])
    else:
        print("out of index2")
else:
    print("out of index1")


index1 8
index2 7


out of index1


In [27]:
fruits=["apple","orange","mango"]
for fruit in fruits:
    print(fruit)
    print(fruit+"pie")

apple
applepie
orange
orangepie
mango
mangopie


In [13]:
fruit=["apple","orange","mango"]
veg=["potato","tomato","onion","bringe"]
dirty_dozen=[fruit,veg]
for index2 in range(0,len(dirty_dozen)):
    for i in dirty_dozen[index2]:
        print(i)
        print(i+"pie")

apple
applepie
orange
orangepie
mango
mangopie
potato
potatopie
tomato
tomatopie
onion
onionpie
bringe
bringepie


In [57]:
def sum_marks():
    marks=[]
    sum1=0
    for i in range (0,n):
        num1=int(input("enter the elements"))
        marks.append(num1)
    return marks
    for j in marks:
        sum1+=j
    return sum1
n=int(input("enter the no elements"))
print(sum_marks())

        
        

            
        

enter the no elements 4
enter the elements 1
enter the elements 1
enter the elements 1
enter the elements 1


[1, 1, 1, 1]
4


In [58]:
n=int(input("enter the limit "))
for i in range (1,n+1):
    if(i%3==0 and i%5==0):
        print("fizzbuzz")
    elif(i%5==0):
        print("fizz")
    elif(i%3==0):
        print("buzz")
    else:
        print(i)
    

enter the limit  50


1
2
buzz
4
fizz
buzz
7
8
buzz
fizz
11
buzz
13
14
fizzbuzz
16
17
buzz
19
fizz
buzz
22
23
buzz
fizz
26
buzz
28
29
fizzbuzz
31
32
buzz
34
fizz
buzz
37
38
buzz
fizz
41
buzz
43
44
fizzbuzz
46
47
buzz
49
fizz


In [59]:
height=float(input("enter height:"))
weight=float(input("enter weight"))
bmi=round(weight/(height*height),2)
print(bmi)
if(18.5<=bmi<=24.99):
    print("normal weight")
elif(25.0<=bmi<=29.99):
    print("over weight")
elif(bmi>=30.0):
    print("obese")
else:
    print("under weight")




enter height: 1.75
enter weight 50


16.33
under weight


In [2]:
name=input("enter first string")
name2=input("enter second string")
name3=[]
name4=[]
c=0
if(len(name)==len(name2)):
    for i in name:
        name3.append(i)
    for j in name2:
        name4.append(j)
    for k in name4:
        if(k in name3):
            c=c+1
            name3.remove(k)
    if(len(name3)==0 and len(name4)==c):
        print("anagram")
    else:
        print("not anagram")

else:
    print("please valid string")






    

enter first string enum
enter second string nume


anagram


In [56]:
password=input("enter a password")
special_charcter=['!','@','#','$','%','^','&','*','(',')','_','+','-','}','{','>','<','?','/','\']']
char=['a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z']
char2=['A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','V','U','W','X','Y','Z']
num=['1','2','3','4','5','6','7','8','9','0']
c=0
c1=0
c2=0
c3=0
c4=0
if(len(password)>=8):
    for i in password:
        if(i in special_charcter):
            c+=1
        elif(i in char):
            c1+=1
        elif(i in char2):
            c2+=1
        elif(i in num):
            c3=c3+1
        else:
            c4=0
    if(c>=1):
        if(c1>=1):
            if(c2>=1):
                if(c3>=1):
                    print("valid password")
                    if(c==2):
                        print("valid")
                    elif(c==4):
                        print("strong")
                    elif(c==8):
                        print("very strong")
                else:
                    print("invalid")
            else:
                print("invalid")
        else:
            print("invalid")
    else:
        print("invalid")
else:
    print("enter minimum 8 character")


enter a password hfgy


enter minimum 8 character


In [69]:
my_list=[1,2,3,4,5,6]
for element in my_list:
    if(element==4):
        break
    else:
        print(element)
        continue 

1
2
3


In [3]:
my_list=[1,2,3,4,5,6]
for element in my_list:
    if(element==4):
        break
    else:
        continue 
        print(element)

In [4]:
my_list=[1,2,3,4,5,6]
for element in my_list:
    if(element==4):
        break
    else:
        pass
        print(element)

1
2
3
