In [29]:
import math
def calc():
    fnum=int(input("enter the first number:"))
    print("would choose your operation \n+\n-\nx\n/\n%\npow()\n^\nsin()\ncos()\ntan()\nsqrt()\nper()")
    oper1=input("enter the opeartion")
    oper=oper1.lower()
    if(oper=='sin()' or oper=='cos()'or oper=='tan()' or oper=='sqrt()' or oper=='per()'):
        if(oper=='sin()'):
            a=math.radians(fnum)
            print(round(math.sin(a),4))
        elif(oper=='cos()'):
            a=math.radians(fnum)
            print(round(math.cos(a),4))
        elif(oper=='tan()'):
           a=math.radians(fnum)
           print(round(math.tan(a),4))
        elif(oper=='sqrt()'):
           print(round(math.sqrt(fnum),4))
        elif(oper=='per()'):
            print(round((fnum/100),2))
    else:
        snum=int(input("enter second number:"))
        if(oper=='+'):
            c=fnum+snum()
            print(fnum+"+"+snum,c)
        elif(oper=='-'):
            c=fnum-snum
            print(fnum+"-"+snum,c)
        elif(oper=='x'):
            c=fnum*snum
            print(fnum+"x"+snum,c)
        elif(oper=='%'):
            c=fnum%snum
            print(fnum+"%"+snum,c)
        elif(oper=='^'):
            c=fnum**snum
            print(fnum+"^"+snum,c)
        elif(oper=='pow()'):
            d=int(input("enter third number:"))
            c=((fnum**snum)%d)
            print(f"power of{fnum} and {snum} and {d} is",c)
        else:
            print("no operation exist")
calc()
            
         
    
        
        
        
    

enter the first number: 3


would choose your operation 
+
-
x
/
%
pow()
^
sin()
cos()
tan()
sqrt()
per()


enter the opeartion pow()
enter second number: 2
enter third number: 3


power of3 and 2 and 3 is 0


In [7]:
import pandas as pd

In [8]:
df=pd.read_csv('car.csv')

In [9]:
print(df.to_string())

                      Car_Name  Year  Selling_Price  Present_Price  Kms_Driven Fuel_Type Seller_Type Transmission  Owner
0                         ritz  2014           3.35          5.590       27000    Petrol      Dealer       Manual      0
1                          sx4  2013           4.75          9.540       43000    Diesel      Dealer       Manual      0
2                         ciaz  2017           7.25          9.850        6900    Petrol      Dealer       Manual      0
3                      wagon r  2011           2.85          4.150        5200    Petrol      Dealer       Manual      0
4                        swift  2014           4.60          6.870       42450    Diesel      Dealer       Manual      0
5                vitara brezza  2018           9.25          9.830        2071    Diesel      Dealer       Manual      0
6                         ciaz  2015           6.75          8.120       18796    Petrol      Dealer       Manual      0
7                      s cross  

In [10]:
print(pd.options.display.max_rows)

60


In [11]:
df1=df.sample(n=10,random_state=1)

In [12]:
print(df1)

                      Car_Name  Year  Selling_Price  Present_Price  \
285                       jazz  2016           7.40          8.500   
248                        i10  2013           4.00          4.600   
150         TVS Apache RTR 180  2011           0.50          0.826   
217                        eon  2016           3.15          4.430   
107  Royal Enfield Thunder 350  2013           1.25          1.500   
206                      xcent  2017           5.75          7.130   
132          Bajaj Avenger 220  2017           0.75          0.950   
73                  etios liva  2011           2.65          5.710   
288                       city  2015           8.40         13.600   
157          Yamaha FZ S V 2.0  2015           0.48          0.840   

     Kms_Driven Fuel_Type Seller_Type Transmission  Owner  
285       15059    Petrol      Dealer    Automatic      0  
248       30000    Petrol      Dealer       Manual      0  
150        6000    Petrol  Individual       Manua

In [8]:
import pandas as pd
date=('01-08-2005','01-08-2005','01-08-2005','01-08-2005','01-08-2005','01-08-2005','01-08-2005','01-08-2005','01-08-2005','01-08-2005')
df=pd.read_csv('car.csv')
df1=df.sample(n=10,random_state=1)
df1['produceddate']=date
df1['markup']='murugar'
print(df1.to_string())

                      Car_Name  Year  Selling_Price  Present_Price  Kms_Driven Fuel_Type Seller_Type Transmission  Owner produceddate   markup
285                       jazz  2016           7.40          8.500       15059    Petrol      Dealer    Automatic      0   01-08-2005  murugar
248                        i10  2013           4.00          4.600       30000    Petrol      Dealer       Manual      0   01-08-2005  murugar
150         TVS Apache RTR 180  2011           0.50          0.826        6000    Petrol  Individual       Manual      0   01-08-2005  murugar
217                        eon  2016           3.15          4.430       15000    Petrol      Dealer       Manual      0   01-08-2005  murugar
107  Royal Enfield Thunder 350  2013           1.25          1.500       15000    Petrol  Individual       Manual      0   01-08-2005  murugar
206                      xcent  2017           5.75          7.130       12479    Petrol      Dealer       Manual      0   01-08-2005  murugar

In [ ]:
df1.to_excel('output.xlsx')

In [15]:
print(pd.read_excel("output.xlsx"))

   Unnamed: 0                   Car_Name  Year  Selling_Price  Present_Price  \
0         285                       jazz  2016           7.40          8.500   
1         248                        i10  2013           4.00          4.600   
2         150         TVS Apache RTR 180  2011           0.50          0.826   
3         217                        eon  2016           3.15          4.430   
4         107  Royal Enfield Thunder 350  2013           1.25          1.500   
5         206                      xcent  2017           5.75          7.130   
6         132          Bajaj Avenger 220  2017           0.75          0.950   
7          73                 etios liva  2011           2.65          5.710   
8         288                       city  2015           8.40         13.600   
9         157          Yamaha FZ S V 2.0  2015           0.48          0.840   

   Kms_Driven Fuel_Type Seller_Type Transmission  Owner produceddate  
0       15059    Petrol      Dealer    Automatic

In [16]:
parsedates=pd.read_excel("output.xlsx",parse_dates=['produceddate'])

In [17]:
print(parsedates.to_string())

   Unnamed: 0                   Car_Name  Year  Selling_Price  Present_Price  Kms_Driven Fuel_Type Seller_Type Transmission  Owner produceddate
0         285                       jazz  2016           7.40          8.500       15059    Petrol      Dealer    Automatic      0   2005-05-08
1         248                        i10  2013           4.00          4.600       30000    Petrol      Dealer       Manual      0   2005-05-08
2         150         TVS Apache RTR 180  2011           0.50          0.826        6000    Petrol  Individual       Manual      0   2005-05-08
3         217                        eon  2016           3.15          4.430       15000    Petrol      Dealer       Manual      0   2005-05-08
4         107  Royal Enfield Thunder 350  2013           1.25          1.500       15000    Petrol  Individual       Manual      0   2005-05-08
5         206                      xcent  2017           5.75          7.130       12479    Petrol      Dealer       Manual      0   200

In [20]:
df1['produced_dates']="05-08-2005"
print(df1.to_string())

                      Car_Name  Year  Selling_Price  Present_Price  Kms_Driven Fuel_Type Seller_Type Transmission  Owner produceddate produced_dates
285                       jazz  2016           7.40          8.500       15059    Petrol      Dealer    Automatic      0   05-08-2005     05-08-2005
248                        i10  2013           4.00          4.600       30000    Petrol      Dealer       Manual      0   05-08-2005     05-08-2005
150         TVS Apache RTR 180  2011           0.50          0.826        6000    Petrol  Individual       Manual      0   05-08-2005     05-08-2005
217                        eon  2016           3.15          4.430       15000    Petrol      Dealer       Manual      0   05-08-2005     05-08-2005
107  Royal Enfield Thunder 350  2013           1.25          1.500       15000    Petrol  Individual       Manual      0   05-08-2005     05-08-2005
206                      xcent  2017           5.75          7.130       12479    Petrol      Dealer      

In [21]:
df1.to_excel('output.xlsx')

In [22]:
df.columns

Index(['Car_Name', 'Year', 'Selling_Price', 'Present_Price', 'Kms_Driven',
       'Fuel_Type', 'Seller_Type', 'Transmission', 'Owner'],
      dtype='object')

In [24]:
df1.columns

Index(['Car_Name', 'Year', 'Selling_Price', 'Present_Price', 'Kms_Driven',
       'Fuel_Type', 'Seller_Type', 'Transmission', 'Owner', 'produceddate',
       'produced_dates'],
      dtype='object')

In [12]:
import pandas as pd
data={
    "calories":[420,380,390],
    "duration":[50,40,45]
}
df=pd.DataFrame(data)
print(df)

   calories  duration
0       420        50
1       380        40
2       390        45


In [13]:
print(df.iloc[0,1])

50


In [14]:
print(df.iloc[0,1])

50


In [15]:
print(df.iloc[0,0])

420


In [20]:
print(df.iloc[0:2,0:2])

   calories  duration
0       420        50
1       380        40


In [17]:
print(df.loc[[0,1][0]])

calories    420
duration     50
Name: 0, dtype: int64


In [56]:
df.to_json('output.json')

In [57]:
pd.read_json("output.json")

calories  duration
0       420        50
1       380        40
2       390        45

In [30]:
import numpy as np

In [35]:
a=np.array(42)
b=np.array([1,2,3,4,5])
c=np.array([[1,2,3],[4,5,6]])
d=np.array([[[1,2,3]],[[4,5,6]],[[6,7,8]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [25]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [26]:
print("5 th element on 2 nd row",arr[-2,-1])

5 th element on 2 nd row 5


In [34]:
np.zeros(4)

array([0., 0., 0., 0.])

In [27]:
a=np.full((2,2),10)
print(a.ndim)

2


In [80]:
a=np.array([1,2,3,4,5,6])
x=a.copy()
a[0]=42
print(x)
print(a)

[1 2 3 4 5 6]
[42  2  3  4  5  6]


In [38]:
a=np.array([1,2,3,4,5,6])
x=a.view()
a[0]=42
print(x)
print(a)
print(x.base)

[42  2  3  4  5  6]
[42  2  3  4  5  6]
[42  2  3  4  5  6]


In [83]:
c=np.array([[1,2,3],[4,5,6]])
print(c.shape)

(2, 3)


In [107]:
a=np.array([1,2,3,4,5,6])
a1=a.reshape(2,3)
print(a.reshape(2,3))
print(a.ndim)
print(a1.ndim)

[[1 2 3]
 [4 5 6]]
1
2


In [110]:
a=np.array([1,2,3,4,5,6,])
a1=a.reshape(1,2,3,1)
print(a1)

[[[[1]
   [2]
   [3]]

  [[4]
   [5]
   [6]]]]


In [40]:
a=np.array([1,2,3,4,5,6,])
a1=a.reshape(1,2,-1)
print(a1)

[[[1 2 3]
  [4 5 6]]]


In [41]:
a=np.array([1,2,3,4,5,6,7,8])
a1=a.reshape(2,4).base
a[4]=19
print(a1)
print(a1.base)

[ 1  2  3  4 19  6  7  8]
None


In [42]:
a=np.array([[1,2,3],[4,5,6]])
print(a.reshape(-1))

[1 2 3 4 5 6]


In [43]:
mean=(99+86+85+86+87+88+111+86+103+87+94+78+77)/13

In [44]:
mean

89.76923076923077

In [45]:
round(-236.4)

-236

In [46]:
round(-236.6)

-237

In [47]:
int(-236.6)

-236

In [48]:
import numpy as np
mean=[99,86,85,86,87,88,111,86,103,87,94,78,77]

In [127]:
print(np.median(mean))

87.0


In [2]:
from scipy import stats 
mean=[99,86,85,86,87,88,111,86,103,87,94,78,77]
print(stats.mode(mean))


ModeResult(mode=np.int64(86), count=np.int64(3))


In [3]:
#find the mean
# subtract the each value from mean
#subract the value square the all the value
#square the all sum of value 

In [5]:
import numpy as np
mean=[99,86,85,86,87,88,111,86,103,87,94,78,77]
np.var(mean)

np.float64(85.71597633136093)

In [6]:
np.std(mean)

np.float64(9.258292301032677)

In [53]:
print(np.ceil(123.1))

124.0


In [51]:
print(np.floor(123.9))

123.0


In [ ]:
import 