In [6]:
import array as arr
arr.array?

Init signature: arr.array(self, /, *args, **kwargs)
Docstring:     
array(typecode [, initializer]) -> array

Return a new array whose items are restricted by typecode, and
initialized from the optional initializer value, which must be a list,
string or iterable over elements of the appropriate type.

Arrays represent basic values and behave very much like lists, except
the type of objects stored in them is constrained. The type is specified
at object creation time by using a type code, which is a single character.
The following type codes are defined:

    Type code   C Type             Minimum size in bytes
    'b'         signed integer     1
    'B'         unsigned integer   1
    'u'         Unicode character  2 (see note)
    'h'         signed integer     2
    'H'         unsigned integer   2
    'i'         signed integer     2
    'I'         unsigned integer   2
    'l'         signed integer     4
    'L'         unsigned integer   4
    'q'         signed integer     8 (s

In [7]:
import array as arr
my_array=arr.array('i',[1,2,3,4,5])
print(my_array)
print(my_array[0])
my_array.append(6)
print(my_array)

array('i', [1, 2, 3, 4, 5])
1
array('i', [1, 2, 3, 4, 5, 6])


In [16]:
import array as arr
my_array=arr.array('I',[-1,-2,-3,-4,-5])
print(my_array)


OverflowError: can't convert negative value to unsigned int

In [17]:
import array as arr
my_array=arr.array('I',[1,2,3,4,5])
print(my_array)


array('I', [1, 2, 3, 4, 5])


In [38]:
import array as arr
my_array=arr.array('i',[1,2,3,4,5])
print(my_array)


array('i', [1, 2, 3, 4, 5])


In [19]:
import numpy as np
numpy_array=np.array([1,2,3,4,5])
print(numpy_array)

[1 2 3 4 5]


In [21]:
import numpy as np
numpy_array=np.array([1,2,3,4,5])
print(numpy_array)
print(numpy_array*2)

[1 2 3 4 5]
[ 2  4  6  8 10]


In [24]:
import numpy as np
multi_dim_array=np.array([[1,2],[3,4]])
print(multi_dim_array)

[[1 2]
 [3 4]]


In [28]:
import random
friends=["pro","kee","sakthi","charu","sri","abi","akshu","lavu"]
print(random.choice(friends))

pro


In [45]:
import kee_module
import random
kee_module.friends     #adding the module file
print(random.choice(friends))

charu


In [52]:
import kee_module
import random
kee_module.friends     #adding the module file
print(random.choice(kee_module.friends))

sakthi


In [56]:
from f_files import friendsfile
from f_files import fruitsfile
print((random.choice(friendsfile.friends)))

sri


In [58]:
import random
friends=["pro","kee","sakthi","charu","sri","abi","akshu","lavu"]
random_index=random.randint(0,4)
print(friends[random_index])

sri


In [62]:
import random
friends=["pro","kee","sakthi","charu","sri","abi","akshu","lavu"]
random_index=random.randint(0,12)
print(friends[random_index])

IndexError: list index out of range

In [63]:
fruits=["Apple","Mango","Graphes","Pine apple","Papaya"]
vegetables=["Spinach","Kale","Tomatoes","Celery","Potatoes"]
dirty_dozen=[fruits,vegetables]
print(type(dirty_dozen))

<class 'list'>


In [64]:
fruits=["Apple","Mango","Graphes","Pine apple","Papaya"]
vegetables=["Spinach","Kale","Tomatoes","Celery","Potatoes"]
dirty_dozen=[fruits,vegetables]
print(dirty_dozen[1][1])

Kale


In [65]:
fruits=["Apple","Mango","Graphes","Pine apple","Papaya"]
vegetables=["Spinach","Kale","Tomatoes","Celery","Potatoes"]
dirty_dozen=[fruits,vegetables]
print(dirty_dozen)

[['Apple', 'Mango', 'Graphes', 'Pine apple', 'Papaya'], ['Spinach', 'Kale', 'Tomatoes', 'Celery', 'Potatoes']]


In [69]:
my_list=["Apple","Mango","Graphes","Pine apple","Papaya"]
random_item=random.choice(my_list)
print(f"Random item: {random_item}") #single random element

random_sample_unique=random.sample(my_list,3)
print(f"Random sample(unique): {random_sample_unique}")  #3 unique random element

random_numbers=


Random item: Pine apple


In [74]:
fruits=["Apples","graphes","peaches"]
veg=["spinach","kale","celery"]
dirty_dozen=[fruits,veg]
index1=random.randint(0,1)
index2=random.randint(0,2)
print(dirty_dozen[int(input("index1"))][int(input("index2"))])

index1 0
index2 2


peaches


In [1]:
fruits=["Apples","graphes","peaches"]
veg=["spinach","kale","celery","drumsticks"]
dirty_dozen=[fruits,veg]
index1=int(input("Enter index1"))
index2=int(input("Enter Index2"))
if(0<=index1<len(dirty_dozen)):
    if(0<=index2<len(fruits) and index1==0):
        print(dirty_dozen[index1][index2])
    elif(0<=index2<len(veg) and index1==1):
        print(dirty_dozen[index1][index2])
    else:
        print("invalid values")
else:
    print("Dirty dozen exceeds values")

Enter index1 2
Enter Index2 0


Dirty dozen exceeds values


In [2]:
fruits=["Apples","graphes","peaches"]
for fruit in fruits:
    print(fruit)
    print(fruit + "Pie")

Apples
ApplesPie
graphes
graphesPie
peaches
peachesPie


In [5]:
fruits=["Apples","graphes","peaches"]
for fruit in fruits:
    print(fruit)
    print(f"{fruit} + Pie")

Apples
Apples + Pie
graphes
graphes + Pie
peaches
peaches + Pie


In [13]:
for index in dirty_dozen:
    for fruits in dirty_dozen[0]:
        print(fruit)
        print(fruit +" pie")

peaches
peaches pie
peaches
peaches pie
peaches
peaches pie
peaches
peaches pie
peaches
peaches pie
peaches
peaches pie


In [16]:
for index in range(0,len(dirty_dozen)):
    for fruit in dirty_dozen[0]:
        print(fruit)
        print(fruit+" Pie")

Apples
Apples Pie
graphes
graphes Pie
peaches
peaches Pie
Apples
Apples Pie
graphes
graphes Pie
peaches
peaches Pie


In [31]:
#1st question
n=int(input("No of elements to be sumed"))
marks=[]
for i in range(0,n):
    marks.append(int(input("Enter Element")))
    total=sum(marks)
    print(total)

No of elements to be sumed 5
Enter Element 1


1


Enter Element 6


7


Enter Element 9


16


Enter Element 6


22


Enter Element 4


26


In [35]:
#2nd question
number=int(input("Enter a number"))
if(number%3==0 and number%5==0):
    print("FizzBuzz")
elif(number%3==0 or number%5==0):
    if(number%3==0):
        print("Fizz")
    else:
        print("Buzz")
else:
    print("Invalid")
    

Enter a number 30


FizzBuzz


In [44]:
#BMI question
weight=input("Enter the weight")
height=input("Enter the height")
weight1=float(weight)
height1=float(height)
bmi=round(weight1/(height1 * height1),2)
print(bmi)
if(bmi<0 and bmi<18.5):
    print("Under weight")
elif(bmi>=18.5 and bmi<24.9):
    print("Normal weight")
elif(bmi>25 and bmi<=29.9):
    print("Over weight")
elif(bmi>=30):
    print("Obesity")
else:
    print("Invalid")



Enter the weight 70
Enter the height 1.75


22.86
Normal weight


In [ ]:
#anagrams
s1=input("Enter a word")
s2=input("Enter a word")


In [56]:
#password check
password=input("Enter a password")
specialchar=["!","@","#","$","%","^","&","*","(",")","-","_","=","+",":",";","<",">","?","/"]
lowcount=0
upcount=0
digitcount=0
charr=0
specialcharr=0
if(len(password)>8):
    for i in password:
        if(i.islower()):
            lowcount +=1
        elif(i.isupper()):
            upcount +=1
        elif(i.isdigit()):
            digitcount+=1
        elif(i in specialchar):
            specialcharr+=1
        else:
            charr+=1
    if(lowcount>=1 and upcount>=1 and digitcount>=1 and specialcharr>=2):
        if(specialcharr==2):
            print("valid")
        elif(specialcharr>2 and specialcharr<=4):
            print("Strong")
        elif(specialcharr>4):
            print("Very strong")
        else:
            print("Not valid special characters")
    else:
        print("Not valid strengh checkers")
else:
    print("Invalid password length")



Enter a password hsDF#$%16473


Strong


In [57]:
mylist=[1,2,3,4,5]
for element in mylist:
    print(element)
    if(element==4):
        break
    else:
        continue
        

1
2
3
4


In [64]:
mylist=[1,2,3,4,5]
for element in mylist:
   
    if(element==4):
        break
    else:
        pass
    print(element)
        

1
2
3


In [73]:
name="keerthika"
charlist=[]
for c in name:
    print(c)
    charlist.append(c)
    list1=charlist
    charlist.sort()

k
e
e
r
t
h
i
k
a


In [79]:
name="keerthika"
charlist=[]
for c in name:
    print(c)
    charlist.append(c)
charlist.sort()



k
e
e
r
t
h
i
k
a


In [81]:
name="keerthika"
sorted_word=sorted(name)
print(name)
print(sorted_word)

keerthika
['a', 'e', 'e', 'h', 'i', 'k', 'k', 'r', 't']


In [ ]:
name="keerthi"
for i in 