In [2]:
import array as arr
my_array=arr.array("i",[1,2,3,4,5])
print(my_array)
print(my_array[0])
my_array.append(6)
print(my_array)


array('i', [1, 2, 3, 4, 5])
1
array('i', [1, 2, 3, 4, 5, 6])


In [9]:
import array as arr
my_array=arr.array("I",[-1,-2,-3,-4,-5])
print(my_array)
print(my_array[0])
my_array.append(-6)
print(my_array)

OverflowError: can't convert negative value to unsigned int

In [10]:
import array as arr
my_array=arr.array("I",[1,2,3,4,5])
print(my_array)
print(my_array[0])
my_array.append(6)
print(my_array)

array('I', [1, 2, 3, 4, 5])
1
array('I', [1, 2, 3, 4, 5, 6])


In [11]:
import array as arr
my_array=arr.array("b",[1,2,3,4,5])
print(my_array)
print(my_array[0])
my_array.append(6)
print(my_array)

array('b', [1, 2, 3, 4, 5])
1
array('b', [1, 2, 3, 4, 5, 6])


In [13]:
import numpy as np
numpy_array=np.array([1,2,3,4,5])
print(numpy_array*2)
multi_dim_array=([1,2],[3,4])
print(multi_dim_array)

[ 2  4  6  8 10]
([1, 2], [3, 4])


In [23]:
import random
friends=["Afsal","Anas","Karthi","Sekar","RK","PK","Subu","Tamil","Vasanth"]
print(random.choice(friends))

Subu


In [27]:
import random
import my_trail
print(random.choice(friends))

Anas


In [34]:
from files1 import my_module
print(random.choice(friends))

Vasanth


In [1]:
import random
friends=["Afsal","Anas","Karthi","Sekar","RK","PK","Subu","Tamil","Vasanth"]
random_index=random.randint(0,2)
print(friends[random_index])

Karthi


In [5]:
import random
friends=["Afsal","Anas","Karthi","Sekar","RK"]
random_index=random.randint(4,6)
print(friends(random_index))

TypeError: 'list' object is not callable

In [3]:
print(friends[6])

IndexError: list index out of range

In [6]:
fruits=["Apple","banana","pomegranate","orange","papaya"]
vegetables=["potato","tomato","brinjal","onion","carrot"]
dirty_dozen=[fruits,vegetables]
print(dirty_dozen[0][1])
print(dirty_dozen[1][2])

banana
brinjal


In [7]:
import random
my_list=["apple","banana","cherry","date","elderberry"]
random_item=random.choice(my_list)
print(f"Random.item:{random_item}")


Random.item:apple


In [9]:
random_sample_unique=random.sample(my_list,3)
print(f"Random sample (unique): {random_sample_unique}")


Random sample (unique): ['elderberry', 'banana', 'apple']


In [16]:
import random

random_numbers = [random.randint(1, 100) for _ in range(5)]
print(f"List of random numbers: {random_numbers}")


List of random numbers: [73, 82, 87, 73, 17]


In [22]:
import random
fruits=["Apple","banana","pomegranate","orange","papaya"]
vegetables=["potato","tomato","brinjal","onion","carrot"]
dirty_dozen=[fruits,vegetables]
index1=random.randint(0,1)
index2=random.randint(0,2)
print(dirty_dozen[int(input("index1: "))][int(input("index2: "))])

index1:  1
index2:  2


brinjal


In [26]:
fruits=["Apple","banana","pomegranate","orange","papaya"]
vegetables=["potato","tomato","brinjal","onion","carrot"]
dirty_dozen=[fruits,vegetables]
index1=int(input(" "))
index2=int(input(" "))
if(0<= index1<len(dirty_dozen)):
    if(0<= index2<len(fruits)and index1==0):
        print(dirty_dozen[index1][index2])
    elif(0<= index2<len(vegetables) and index1==1):
        print(dirty_dozen[index1][index2])
    else:
        print("out of index")
else:
    print("Invalid")
         
 

  1
  2


brinjal


In [29]:
for fruit in fruits:
    print(fruit)
    print(fruit+"pie")

Apple
Applepie
banana
bananapie
pomegranate
pomegranatepie
orange
orangepie
papaya
papayapie


In [41]:
fruits=["Apple","banana","pomegranate","orange","papaya"]
vegetables=["potato","tomato","brinjal","onion","carrot"]
dirty_dozen=[fruits,vegetables]
for index in range(0,len(dirty_dozen)):
    for fruit in dirty_dozen[index]:
        print(fruit)
        print(f"{fruit} pie")


Apple
Apple pie
banana
banana pie
pomegranate
pomegranate pie
orange
orange pie
papaya
papaya pie
potato
potato pie
tomato
tomato pie
brinjal
brinjal pie
onion
onion pie
carrot
carrot pie


In [42]:
def sum_marks(my_list):
    total = 0
    for num in my_list:
        total += num
    return total

marks = [50, 60, 70]
print(sum_marks(marks))

  
 
          
    


180


In [44]:
num=[1,3,5,7,9]
print(sum(num))

25


In [48]:
n=[1,2,3,4,5]
s=0
for a in  n:
    s+=a
print(s)
 

15


In [1]:
#summarks
def SumMarks():
    num = int(input("Enter the number of marks: "))
    marks = [] 
    for a in range(num):
        value = int(input("Enter element: "))
        marks.append(value)
    total = 0
    for i in marks:
        total += i
    print("Total sum of marks:", total)
SumMarks()


    

Enter the number of marks:  5
Enter element:  1
Enter element:  5
Enter element:  2
Enter element:  3
Enter element:  4


Total sum of marks: 15


In [13]:
#fizzbuzz
num=int(input("Enter number:"))
for i in range(0,num):  
    if i % 3 == 0 and i % 5 == 0:
        print("FizzBuzz")  
    elif i % 3 == 0:
        print("Fizz")     
    elif i % 5 == 0:
        print("Buzz")      
    else:
        print(i)       

        

Enter number: 21


FizzBuzz
1
2
Fizz
4
Buzz
Fizz
7
8
Fizz
Buzz
11
Fizz
13
14
FizzBuzz
16
17
Fizz
19
Buzz


In [7]:
#BMI
weight = float(input("Enter your weight in kg: "))
height = float(input("Enter your height in meters: "))
bmi = weight / (height ** 2)
print(f"Your BMI is: {bmi:.2f}")
if bmi < 18.5:
    print("You are Underweight.")
elif 18.5 <= bmi < 24.9:
    print("You are Normal weight.")
elif 25 <= bmi < 29.9:
    print("You are Overweight.")
else:
    print("You are Obesity.")



Enter your weight in kg:  70
Enter your height in meters:  1.68


Your BMI is: 24.80
You are Normal weight.


In [11]:
# Anagram 
s1 = input("Enter first string: ")
s2 = input("Enter second string: ")
s1 = s1.replace(" ", "").lower()
s2 = s2.replace(" ", "").lower()
if sorted(s1) == sorted(s2):
    print("The strings are anagrams!")
else:
    print("The strings are NOT anagrams.")


Enter first string:  ganesh
Enter second string:  aneshg


The strings are anagrams!


In [14]:
s1 = input("Enter first string: ")
s2 = input("Enter second string: ")
s1 = s1.replace(" ", "").lower()
s2 = s2.replace(" ", "").lower()
if len(s1) != len(s2):
    print(" Not anagrams")
else:
    is_anagram = True
    for ch in s1:
        if s1.count(ch) != s2.count(ch):
            is_anagram = False
            break
    if is_anagram:
        print(" The strings are anagrams!")
    else:
        print(" The strings are NOT anagrams.")

    

Enter first string:  listen
Enter second string:  silent


 The strings are anagrams!


In [1]:
def check_password_strength(password):
    special_chars = ".!@#$%^&*'\"-_=+;:,"
    has_lower = any(c.islower() for c in password)
    has_upper = any(c.isupper() for c in password)
    has_digit = any(c.isdigit() for c in password)
    special_count = sum(c in special_chars for c in password)
    length = len(password) >= 8
    if not length:
        print(" Password must be at least 8 characters long.")
        return
    if not has_lower:
        print(" Password must contain at least one lowercase letter.")
        return
    if not has_upper:
        print(" Password must contain at least one uppercase letter.")
        return
    if not has_digit:
        print(" Password must contain at least one digit.")
        return
    if special_count < 2:
        print(" Password must contain at least 2 special characters.")
        return
    if special_count == 2:
        print(" Password is Valid.")
    elif 2 < special_count <= 4:
        print(" Password is Strong.")
    else:
        print(" Password is Very Strong!")
password = input("Enter your password: ")
check_password_strength(password)


Enter your password:  Gr13.11@2002


 Password is Valid.


In [1]:
my_list=[1,2,3,4,5]
for element in my_list:
    if(element==4):
        break
    else:
        pass
    print(element)
    

1
2
3


In [5]:
my_word="listen"
checklist=[]
for c in my_word:
    checklist.append(c)
    list1=checklist
    checklist.sort()
print(checklist)

['e', 'i', 'l', 'n', 's', 't']


In [3]:
my_list=[1,2,3,4,5]
for element in my_list:
    print(element)
    if(element==4):
        break
    else:
        continue
        

1
2
3
4


In [ ]:
text = input("Enter a string: ")
char_list = []
for ch in text:
    char_list += [ch]  
for i in range(len(char_list)):
    for j in range(i + 1, len(char_list)):
        if char_list[i] > char_list[j]:
            temp = char_list[i]
            char_list[i] = char_list[j]
            char_list[j] = temp
sorted_text = ""
for ch in char_list:
    sorted_text += ch

print("Sorted string:", sorted_text)


In [2]:
import numpy as np
a=np.zeros(3)
a

array([0., 0., 0.])

In [3]:
z=np.zeros(10)
z



array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
z.shape

(10,)

In [10]:
z.shape=(10,1)
z

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [9]:
z=np.ones(10)
z

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [12]:
z=np.empty(3)
z

array([0.00000000e+000, 0.00000000e+000, 1.01855798e-311])

In [18]:
import numpy as np
z = np.linspace(2, 10, 5)

print(z)

[ 2.  4.  6.  8. 10.]


In [21]:
z=np.array([10,20])
z

array([10, 20])

In [22]:
a_list=[1,2,3,4,5,6,7,8,9]
z=np.array([a_list])
z

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [23]:
type(z)

numpy.ndarray

In [24]:
b_list=[[9,8,7,6,5,4,3,2,1],[1,2,3,4,5,6,7,8,9]]
z=np.array([b_list])
z

array([[[9, 8, 7, 6, 5, 4, 3, 2, 1],
        [1, 2, 3, 4, 5, 6, 7, 8, 9]]])

In [29]:
z.shape
?



IPython -- An enhanced Interactive Python

IPython offers a fully compatible replacement for the standard Python
interpreter, with convenient shell features, special commands, command
history mechanism and output results caching.

At your system command line, type 'ipython -h' to see the command line
options available. This document only describes interactive features.

GETTING HELP
------------

Within IPython you have various way to access help:

  ?         -> Introduction and overview of IPython's features (this screen).
  object?   -> Details about 'object'.
  object??  -> More detailed, verbose information about 'object'.
  %quickref -> Quick reference of all IPython specific syntax and magics.
  help      -> Access Python's own help system.

If you are in terminal IPython you can quit this screen by pressing `q`.


MAIN FEATURES
-------------

* Access to the standard Python help with object docstrings and the Python
  manuals. Simply type 'help' (no quotes) to invoke it.

* Ma

In [30]:
z.shape

(1, 2, 9)

In [31]:
z.shape
?z.shape

Type:        tuple
String form: (1, 2, 9)
Length:      3
Docstring:  
Built-in immutable sequence.

If no argument is given, the constructor returns an empty tuple.
If iterable is specified the tuple is initialized from iterable's items.

If the argument is a tuple, the return value is the same object.

In [32]:
np.random.seed(0)
z1=np.random.randint(10,size=6)
z1



array([5, 0, 3, 3, 7, 9], dtype=int32)

In [33]:
z1[0]
z1[0:2]
z1[-1]


np.int32(9)

In [34]:
z1[0]

np.int32(5)

In [35]:
z1[0:2]

array([5, 0], dtype=int32)

In [36]:
z1[-1]

np.int32(9)

In [39]:
np.std?

Signature:      
np.std(
    a,
    axis=None,
    dtype=None,
    out=None,
    ddof=0,
    keepdims=<no value>,
    *,
    where=<no value>,
    mean=<no value>,
    correction=<no value>,
)
Call signature:  np.std(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function std at 0x000001E069544220>
File:            c:\users\user 10\anaconda3\lib\site-packages\numpy\_core\fromnumeric.py
Docstring:      
Compute the standard deviation along the specified axis.

Returns the standard deviation, a measure of the spread of a distribution,
of the array elements. The standard deviation is computed for the
flattened array by default, otherwise over the specified axis.

Parameters
----------
a : array_like
    Calculate the standard deviation of these values.
axis : None or int or tuple of ints, optional
    Axis or axes along which the standard deviation is computed. The
    default is to compute the standard deviation of the flattened array.

    .. versionadded::

In [38]:
np.mean?

Signature:      
np.mean(
    a,
    axis=None,
    dtype=None,
    out=None,
    keepdims=<no value>,
    *,
    where=<no value>,
)
Call signature:  np.mean(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function mean at 0x000001E0695440E0>
File:            c:\users\user 10\anaconda3\lib\site-packages\numpy\_core\fromnumeric.py
Docstring:      
Compute the arithmetic mean along the specified axis.

Returns the average of the array elements.  The average is taken over
the flattened array by default, otherwise over the specified axis.
`float64` intermediate and return values are used for integer inputs.

Parameters
----------
a : array_like
    Array containing numbers whose mean is desired. If `a` is not an
    array, a conversion is attempted.
axis : None or int or tuple of ints, optional
    Axis or axes along which the means are computed. The default is to
    compute the mean of the flattened array.

    .. versionadded:: 1.7.0

    If this is a tuple

In [40]:
np.var?

Signature:      
np.var(
    a,
    axis=None,
    dtype=None,
    out=None,
    ddof=0,
    keepdims=<no value>,
    *,
    where=<no value>,
    mean=<no value>,
    correction=<no value>,
)
Call signature:  np.var(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function var at 0x000001E069544360>
File:            c:\users\user 10\anaconda3\lib\site-packages\numpy\_core\fromnumeric.py
Docstring:      
Compute the variance along the specified axis.

Returns the variance of the array elements, a measure of the spread of a
distribution.  The variance is computed for the flattened array by
default, otherwise over the specified axis.

Parameters
----------
a : array_like
    Array containing numbers whose variance is desired.  If `a` is not an
    array, a conversion is attempted.
axis : None or int or tuple of ints, optional
    Axis or axes along which the variance is computed.  The default is to
    compute the variance of the flattened array.

    .. versi

In [41]:
np.min?

Signature:      
np.min(
    a,
    axis=None,
    out=None,
    keepdims=<no value>,
    initial=<no value>,
    where=<no value>,
)
Call signature:  np.min(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function min at 0x000001E0695337E0>
File:            c:\users\user 10\anaconda3\lib\site-packages\numpy\_core\fromnumeric.py
Docstring:      
Return the minimum of an array or minimum along an axis.

Parameters
----------
a : array_like
    Input data.
axis : None or int or tuple of ints, optional
    Axis or axes along which to operate.  By default, flattened input is
    used.

    .. versionadded:: 1.7.0

    If this is a tuple of ints, the minimum is selected over multiple axes,
    instead of a single axis or all the axes as before.
out : ndarray, optional
    Alternative output array in which to place the result.  Must
    be of the same shape and buffer length as the expected output.
    See :ref:`ufuncs-output-type` for more details.

keepdims : b

In [42]:
np.max?

Signature:      
np.max(
    a,
    axis=None,
    out=None,
    keepdims=<no value>,
    initial=<no value>,
    where=<no value>,
)
Call signature:  np.max(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function max at 0x000001E0695336A0>
File:            c:\users\user 10\anaconda3\lib\site-packages\numpy\_core\fromnumeric.py
Docstring:      
Return the maximum of an array or maximum along an axis.

Parameters
----------
a : array_like
    Input data.
axis : None or int or tuple of ints, optional
    Axis or axes along which to operate.  By default, flattened input is
    used.

    .. versionadded:: 1.7.0

    If this is a tuple of ints, the maximum is selected over multiple axes,
    instead of a single axis or all the axes as before.
out : ndarray, optional
    Alternative output array in which to place the result.  Must
    be of the same shape and buffer length as the expected output.
    See :ref:`ufuncs-output-type` for more details.

keepdims : b

In [43]:
z<3

array([[[False, False, False, False, False, False, False,  True,  True],
        [ True,  True, False, False, False, False, False, False, False]]])

In [44]:
z>3

array([[[ True,  True,  True,  True,  True,  True, False, False, False],
        [False, False, False,  True,  True,  True,  True,  True,  True]]])

In [45]:
z[z>3]

array([9, 8, 7, 6, 5, 4, 4, 5, 6, 7, 8, 9])

In [46]:
a_array=np.array([1,2,3,4,5])
b_array=np.array([5,4,3,2,1])

In [48]:
a_array+b_array

array([6, 6, 6, 6, 6])

In [49]:
a_array+30

array([31, 32, 33, 34, 35])

In [50]:
a_array*b_array

array([5, 8, 9, 8, 5])

In [51]:
a_array*10

array([10, 20, 30, 40, 50])

In [52]:
a_array@b_array

np.int64(35)

In [53]:
np.sort(z)

array([[[1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9]]])