In [1]:
import pandas as pd
df=pd.read_csv("car.csv")
print(df.to_string())


                      Car_Name  Year  Selling_Price  Present_Price  Kms_Driven Fuel_Type Seller_Type Transmission  Owner
0                         ritz  2014           3.35          5.590       27000    Petrol      Dealer       Manual      0
1                          sx4  2013           4.75          9.540       43000    Diesel      Dealer       Manual      0
2                         ciaz  2017           7.25          9.850        6900    Petrol      Dealer       Manual      0
3                      wagon r  2011           2.85          4.150        5200    Petrol      Dealer       Manual      0
4                        swift  2014           4.60          6.870       42450    Diesel      Dealer       Manual      0
5                vitara brezza  2018           9.25          9.830        2071    Diesel      Dealer       Manual      0
6                         ciaz  2015           6.75          8.120       18796    Petrol      Dealer       Manual      0
7                      s cross  

In [2]:
print(pd.options.display.max_rows)
 

60


In [3]:
pd.options.display.max_rows = 9999

print(df)
 

                      Car_Name  Year  Selling_Price  Present_Price  \
0                         ritz  2014           3.35          5.590   
1                          sx4  2013           4.75          9.540   
2                         ciaz  2017           7.25          9.850   
3                      wagon r  2011           2.85          4.150   
4                        swift  2014           4.60          6.870   
5                vitara brezza  2018           9.25          9.830   
6                         ciaz  2015           6.75          8.120   
7                      s cross  2015           6.50          8.610   
8                         ciaz  2016           8.75          8.890   
9                         ciaz  2015           7.45          8.920   
10                    alto 800  2017           2.85          3.600   
11                        ciaz  2015           6.85         10.380   
12                        ciaz  2015           7.50          9.940   
13                  

In [4]:
dates = ['dd\mm\yyyy']
df1=df.sample(n=10,random_state=1)
print(df1)

                      Car_Name  Year  Selling_Price  Present_Price  \
285                       jazz  2016           7.40          8.500   
248                        i10  2013           4.00          4.600   
150         TVS Apache RTR 180  2011           0.50          0.826   
217                        eon  2016           3.15          4.430   
107  Royal Enfield Thunder 350  2013           1.25          1.500   
206                      xcent  2017           5.75          7.130   
132          Bajaj Avenger 220  2017           0.75          0.950   
73                  etios liva  2011           2.65          5.710   
288                       city  2015           8.40         13.600   
157          Yamaha FZ S V 2.0  2015           0.48          0.840   

     Kms_Driven Fuel_Type Seller_Type Transmission  Owner  
285       15059    Petrol      Dealer    Automatic      0  
248       30000    Petrol      Dealer       Manual      0  
150        6000    Petrol  Individual       Manua

In [5]:
dates = ['10-01-2004','11-01-2004','12-01-2004','13-01-2004','14-01-2004','15-01-2004','16-01-2004','17-01-2004','18-01-2004','19-01-2004']
df1=df.sample(n=10,random_state=1)
#df1['datesPurchased']=dates
print(df1)

                      Car_Name  Year  Selling_Price  Present_Price  \
285                       jazz  2016           7.40          8.500   
248                        i10  2013           4.00          4.600   
150         TVS Apache RTR 180  2011           0.50          0.826   
217                        eon  2016           3.15          4.430   
107  Royal Enfield Thunder 350  2013           1.25          1.500   
206                      xcent  2017           5.75          7.130   
132          Bajaj Avenger 220  2017           0.75          0.950   
73                  etios liva  2011           2.65          5.710   
288                       city  2015           8.40         13.600   
157          Yamaha FZ S V 2.0  2015           0.48          0.840   

     Kms_Driven Fuel_Type Seller_Type Transmission  Owner  
285       15059    Petrol      Dealer    Automatic      0  
248       30000    Petrol      Dealer       Manual      0  
150        6000    Petrol  Individual       Manua

In [6]:
df1['datePurchased']=dates
print(df1.to_string())

                      Car_Name  Year  Selling_Price  Present_Price  Kms_Driven Fuel_Type Seller_Type Transmission  Owner datePurchased
285                       jazz  2016           7.40          8.500       15059    Petrol      Dealer    Automatic      0    10-01-2004
248                        i10  2013           4.00          4.600       30000    Petrol      Dealer       Manual      0    11-01-2004
150         TVS Apache RTR 180  2011           0.50          0.826        6000    Petrol  Individual       Manual      0    12-01-2004
217                        eon  2016           3.15          4.430       15000    Petrol      Dealer       Manual      0    13-01-2004
107  Royal Enfield Thunder 350  2013           1.25          1.500       15000    Petrol  Individual       Manual      0    14-01-2004
206                      xcent  2017           5.75          7.130       12479    Petrol      Dealer       Manual      0    15-01-2004
132          Bajaj Avenger 220  2017           0.75    

In [9]:
df1["datesPurchased"]=dates
print(df1.to_string())

                      Car_Name  Year  Selling_Price  Present_Price  Kms_Driven Fuel_Type Seller_Type Transmission  Owner datePurchased datesPurchased
285                       jazz  2016           7.40          8.500       15059    Petrol      Dealer    Automatic      0    10-01-2004     10-01-2004
248                        i10  2013           4.00          4.600       30000    Petrol      Dealer       Manual      0    11-01-2004     11-01-2004
150         TVS Apache RTR 180  2011           0.50          0.826        6000    Petrol  Individual       Manual      0    12-01-2004     12-01-2004
217                        eon  2016           3.15          4.430       15000    Petrol      Dealer       Manual      0    13-01-2004     13-01-2004
107  Royal Enfield Thunder 350  2013           1.25          1.500       15000    Petrol  Individual       Manual      0    14-01-2004     14-01-2004
206                      xcent  2017           5.75          7.130       12479    Petrol      Dealer

In [10]:
df.to_excel("output.xlsx")
pd.read_excel("output.xlsx")

Unnamed: 0                   Car_Name  Year  Selling_Price  \
0             0                       ritz  2014           3.35   
1             1                        sx4  2013           4.75   
2             2                       ciaz  2017           7.25   
3             3                    wagon r  2011           2.85   
4             4                      swift  2014           4.60   
5             5              vitara brezza  2018           9.25   
6             6                       ciaz  2015           6.75   
7             7                    s cross  2015           6.50   
8             8                       ciaz  2016           8.75   
9             9                       ciaz  2015           7.45   
10           10                   alto 800  2017           2.85   
11           11                       ciaz  2015           6.85   
12           12                       ciaz  2015           7.50   
13           13                     ertiga  2015           6.10   
14           14                      dzire  2009           2.25   
15           15                     ertiga  2016           7.75   
16           16                     ertiga  2015           7.25   
17           17                     ertiga  2016           7.75   
18           18                    wagon r  2015           3.25   
19           19                        sx4  2010           2.65   
20           20                   alto k10  2016           2.85   
21           21                      ignis  2017           4.90   
22           22                        sx4  2011           4.40   
23           23                   alto k10  2014           2.50   
24           24                    wagon r  2013           2.90   
25           25                      swift  2011           3.00   
26           26                      swift  2013           4.15   
27           27                      swift  2017           6.00   
28           28                   alto k10  2010           1.95   
29           29                       ciaz  2015           7.45   
30           30                       ritz  2012           3.10   
31           31                       ritz  2011           2.35   
32           32                      swift  2014           4.95   
33           33                     ertiga  2014           6.00   
34           34                      dzire  2014           5.50   
35           35                        sx4  2011           2.95   
36           36                      dzire  2015           4.65   
37           37                        800  2003           0.35   
38           38                   alto k10  2016           3.00   
39           39                        sx4  2003           2.25   
40           40                     baleno  2016           5.85   
41           41                   alto k10  2014           2.55   
42           42                        sx4  2008           1.95   
43           43                      dzire  2014           5.50   
44           44                       omni  2012           1.25   
45           45                       ciaz  2014           7.50   
46           46                       ritz  2013           2.65   
47           47                    wagon r  2006           1.05   
48           48                     ertiga  2015           5.80   
49           49                       ciaz  2017           7.75   
50           50                   fortuner  2012          14.90   
51           51                   fortuner  2015          23.00   
52           52                     innova  2017          18.00   
53           53                   fortuner  2013          16.00   
54           54                     innova  2005           2.75   
55           55              corolla altis  2009           3.60   
56           56                etios cross  2015           4.50   
57           57              corolla altis  2010           4.75   
58           58                    etios g  2014    

In [18]:
df.to_excel("output.xlsx")

In [15]:
newParsedDates=pd.read_excel("output.xlsx",parse_dates=[10])


In [16]:
newParsedDatesColumnName=pd.read_excel("output.xlsx",parse_dates=["datesPurchased"])

In [17]:
newParsedDatesColumnName

Unnamed: 0                   Car_Name  Year  Selling_Price  Present_Price  \
0         285                       jazz  2016           7.40          8.500   
1         248                        i10  2013           4.00          4.600   
2         150         TVS Apache RTR 180  2011           0.50          0.826   
3         217                        eon  2016           3.15          4.430   
4         107  Royal Enfield Thunder 350  2013           1.25          1.500   
5         206                      xcent  2017           5.75          7.130   
6         132          Bajaj Avenger 220  2017           0.75          0.950   
7          73                 etios liva  2011           2.65          5.710   
8         288                       city  2015           8.40         13.600   
9         157          Yamaha FZ S V 2.0  2015           0.48          0.840   

   Kms_Driven Fuel_Type Seller_Type Transmission  Owner datePurchased  \
0       15059    Petrol      Dealer    Automatic      0    10-01-2004   
1       30000    Petrol      Dealer       Manual      0    11-01-2004   
2        6000    Petrol  Individual       Manual      0    12-01-2004   
3       15000    Petrol      Dealer       Manual      0    13-01-2004   
4       15000    Petrol  Individual       Manual      0    14-01-2004   
5       12479    Petrol      Dealer       Manual      0    15-01-2004   
6        3500    Petrol  Individual       Manual      0    16-01-2004   
7       43000    Petrol      Dealer       Manual      0    17-01-2004   
8       34000    Petrol      Dealer       Manual      0    18-01-2004   
9       23000    Petrol  Individual       Manual      0    19-01-2004   

  datesPurchased  
0     10-01-2004  
1     11-01-2004  
2     12-01-2004  
3     13-01-2004  
4     14-01-2004  
5     15-01-2004  
6     16-01-2004  
7     17-01-2004  
8     18-01-2004  
9     19-01-2004

In [20]:
data={
    "calories": [420,300,390], "duration" : [50,40,45]}
df=pd.DataFrame(data)
print(df)

   calories  duration
0       420        50
1       300        40
2       390        45


In [29]:
print(df.loc(0))
print(df.iloc(0))
print(df.loc[0])

calories    420
duration     50
Name: 0, dtype: int64


In [30]:
print(df.iloc[0,1])
print(df.iloc[2,1])

50
45


In [31]:
print(df.iloc[0:1,0:1])

   calories
0       420


In [37]:
print(df.loc[[0, 1][0]])

calories    420
duration     50
Name: 0, dtype: int64


In [40]:
df.to_json(orient='split')

'{"columns":["calories","duration"],"index":[0,1,2],"data":[[420,50],[300,40],[390,45]]}'

In [45]:
pd.to_json(orient='index')

AttributeError: module 'pandas' has no attribute 'to_json'

In [46]:
import pandas as pd

# Sample DataFrame
df = pd.DataFrame({
    "datesPurchased": ["2024-02-03", "2025-04-09", "2023-08-15"],
    "car_model": ["Honda", "Toyota", "Ford"],
    "price": [20000, 25000, 18000]
})

# Convert DataFrame to JSON string with orient='index'
json_str = df.to_json(orient='index')

# Print JSON string
print(json_str)


{"0":{"datesPurchased":"2024-02-03","car_model":"Honda","price":20000},"1":{"datesPurchased":"2025-04-09","car_model":"Toyota","price":25000},"2":{"datesPurchased":"2023-08-15","car_model":"Ford","price":18000}}


In [50]:
import numpy as np
a=np.array(42)
b=np.array([1,2,3,4,5])
c=np.array([[1,2,3],[4,5,6]])
d=np.array([[[1,2,3],[4,5,6,]],[[1,2,3],[4,5,6]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)



0
1
2
3


In [52]:
arr=np.array([[1,2,3,4,5],
              [6,7,8,9,10]])
print("2nd element on the First row:",arr[0,1])

2nd element on the First row: 2


In [54]:
arr=np.array([[1,2,3,4,5],
              [6,7,8,9,10]])
print("last element on the second row:",arr[-1,-1])

last element on the second row: 10


In [56]:
np.zeros?


Docstring:
zeros(shape, dtype=float, order='C', *, like=None)

Return a new array of given shape and type, filled with zeros.

Parameters
----------
shape : int or tuple of ints
    Shape of the new array, e.g., ``(2, 3)`` or ``2``.
dtype : data-type, optional
    The desired data-type for the array, e.g., `numpy.int8`.  Default is
    `numpy.float64`.
order : {'C', 'F'}, optional, default: 'C'
    Whether to store multi-dimensional data in row-major
    (C-style) or column-major (Fortran-style) order in
    memory.
like : array_like, optional
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it ensures the creation of an array object
    compatible with that passed in via this argument.

    .. versionadded:: 1.20.0

Returns
-------
out : ndarray
    Array of zeros with the given shape, dtype, and order.

See Al

In [57]:
np.ones?


Signature: np.ones(shape, dtype=None, order='C', *, device=None, like=None)
Docstring:
Return a new array of given shape and type, filled with ones.

Parameters
----------
shape : int or sequence of ints
    Shape of the new array, e.g., ``(2, 3)`` or ``2``.
dtype : data-type, optional
    The desired data-type for the array, e.g., `numpy.int8`.  Default is
    `numpy.float64`.
order : {'C', 'F'}, optional, default: C
    Whether to store multi-dimensional data in row-major
    (C-style) or column-major (Fortran-style) order in
    memory.
device : str, optional
    The device on which to place the created array. Default: None.
    For Array-API interoperability only, so must be ``"cpu"`` if passed.

    .. versionadded:: 2.0.0
like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In thi

In [58]:
np.full?

Signature:
np.full(
    shape,
    fill_value,
    dtype=None,
    order='C',
    *,
    device=None,
    like=None,
)
Docstring:
Return a new array of given shape and type, filled with `fill_value`.

Parameters
----------
shape : int or sequence of ints
    Shape of the new array, e.g., ``(2, 3)`` or ``2``.
fill_value : scalar or array_like
    Fill value.
dtype : data-type, optional
    The desired data-type for the array  The default, None, means
     ``np.array(fill_value).dtype``.
order : {'C', 'F'}, optional
    Whether to store multidimensional data in C- or Fortran-contiguous
    (row- or column-wise) order in memory.
device : str, optional
    The device on which to place the created array. Default: None.
    For Array-API interoperability only, so must be ``"cpu"`` if passed.

    .. versionadded:: 2.0.0
like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
     

In [59]:
np.inf?

Type:        float
String form: inf
Docstring:   Convert a string or number to a floating-point number, if possible.

In [60]:
arr=np.array([1,2,3,4,5])
x=arr.copy()
arr[0]=42
print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [61]:
arr=np.array([1,2,3,4,5])
x=arr.view()
arr[0]=42
print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [2]:
import numpy as np

arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8]])
print(arr.shape)

(2, 4)


In [3]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [5]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,12])
newarr = arr.reshape(4,3)
print(newarr)

ValueError: cannot reshape array of size 11 into shape (4,3)

In [7]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(3,3)
print(newarr)

ValueError: cannot reshape array of size 12 into shape (3,3)

In [8]:
arr=np.array([1,2,3,4,5,6,7,8])
print(arr.reshape(2,4))

[[1 2 3 4]
 [5 6 7 8]]


In [9]:
arr=np.array([1,2,3,4,5,6,7,8])
print(arr.reshape(-1))

[1 2 3 4 5 6 7 8]


In [14]:
mean=(81+85+99+84+87+88+111+86+103+87+94+78+77)/13

print(mean)

89.23076923076923


In [16]:
import numpy 
speed=(81,85,99,84,87,88,111,86,103,87,94,78,77)
x=numpy.median(speed)
print(x)

87.0
