## Create a NumPy array of integers from 1 to 12 and reshape it into a 3×4 matrix.

In [ ]:
import numpy as np

In [7]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(3,4)
print(newarr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [8]:
arr = np.arange(1, 13).reshape(3, 4)


In [9]:
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


## Compute the mean, median, and standard deviation of a random array of size 10 drawn from a uniform distribution between 0 and 1.

In [47]:
import numpy as np

In [48]:
number=[12,23,33,55,67,3423,455]
a=np.array(number)
x=np.mean(number)
print(x)

581.1428571428571


In [49]:
number=np.random.rand(10)

In [50]:
print(number)

[0.39229272 0.5483915  0.96709508 0.51443244 0.09422422 0.20974092
 0.52901746 0.36201107 0.26895209 0.86244111]


In [51]:
print(f" Mean: {(np.mean(number))}")

 Mean: 0.47485986190719565


In [52]:
print(f" Median: {(np.median(number))}")

 Median: 0.4533625806512522


In [53]:
print(f" Std deviation: {np.std(number)}")

 Std deviation: 0.26068034320639244


## Given two NumPy arrays a = [1,2,3,4] and b = [2,2,10,4], find the element-wise comparison (equal, greater, less).

In [4]:
import numpy as np

In [5]:
arr=np.array([1,2,3,4,5])
arr1=np.array([6,7,8,9,10])
print(f" Equal:{np.equal(arr,arr1)}")

 Equal:[False False False False False]


In [6]:
print(f" Greater:{np.greater(arr,arr1)}")

 Greater:[False False False False False]


In [7]:
print(f" Lesser: {np.less(arr,arr1)}")

 Lesser: [ True  True  True  True  True]


In [8]:
arr1 = np.array([[1, 2, 3],
                              [4, 5, 6]])

In [9]:
np.transpose(arr1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [1]:
print("Vertical Stack:\n" np.vstack((arr, arr1)))

print("Horizontal Stack:\n" np.hstack((arr, arr1)))
 

SyntaxError: invalid syntax. Perhaps you forgot a comma? (1999812510.py, line 1)

## Create a 5×5 matrix where each element is the sum of its row and column indices.

In [ ]:
import numpy as np

In [11]:
col=np.arange(5).reshape(5,1)   ##column
print(col)


[[0]
 [1]
 [2]
 [3]
 [4]]


In [12]:
row=np.arange(5)   ##row 1
print(row)


[0 1 2 3 4]


In [13]:
Sum =row + col

## Create a Pandas DataFrame from a dictionary containing columns 'Name', 'Age', and 'City'.

In [54]:
import pandas as pd

In [55]:
data = {'Name': ['Asha', 'Ravi', 'Seema'],
'Age': [25, 30, 28],
'City': ['Bangalore', 'Chennai', 'Pune']}

In [56]:
df = pd.DataFrame(data)

In [57]:
print(df)

    Name  Age       City
0   Asha   25  Bangalore
1   Ravi   30    Chennai
2  Seema   28       Pune


In [58]:
print(data["Name"])

['Asha', 'Ravi', 'Seema']


In [59]:
data ["City"]=['Bangalore','Chennai','Pune']

In [60]:
print(data["Age"])

[25, 30, 28]


In [61]:
data["City"]="Kolkatta"    ##replace the value

In [62]:
print(data["City"])

Kolkatta


In [63]:
for city in data["City"]:
    print(city)

K
o
l
k
a
t
t
a


In [64]:
data["City"].append("Kolkata")

AttributeError: 'str' object has no attribute 'append'

In [65]:
print(data["City"])

Kolkatta


In [26]:
print(pd.DataFrame(data))

    Name  Age      City
0   Asha   25  Kolkatta
1   Ravi   30  Kolkatta
2  Seema   28  Kolkatta


In [27]:
df

Name  Age       City
0   Asha   25  Bangalore
1   Ravi   30    Chennai
2  Seema   28       Pune

## Filter rows from a DataFrame where Age are greater than 26.
 

In [28]:
Filtered_df=df[(df['Age'] > 26)]

 

In [29]:
Filtered_df

Name  Age     City
1   Ravi   30  Chennai
2  Seema   28     Pune

## Given a DataFrame with columns ['Region', 'Sales', 'Profit'], compute total sales and average profit by region.

In [30]:
Sales_data = {
'Region': ['North', 'South', 'North', 'East', 'South'],
'Sales': [5000, 7000, 6000, 4500, 8000],
'Profit': [500, 700, 600, 450, 800]
}

In [31]:
Sales_df=pd.DataFrame(Sales_data)

In [32]:
# SELECT region,sum(sales),avg(profit) FROM Sales_df GROUP BY Region

In [33]:
summary = Sales_df.groupby('Region').agg({'Sales': 'sum', 'Profit': 'mean'})

In [34]:
print(summary)

        Sales  Profit
Region               
East     4500   450.0
North   11000   550.0
South   15000   750.0


## Implement the min, max & sum 

In [35]:
import numpy as np

In [36]:
num=[12,34,54,56,78]
least=np.min(num)

In [37]:
print(least)

12


In [38]:
greatest=np.max(num)

In [39]:
print(greatest)

78


In [40]:
add=np.sum(num)

In [42]:
print(add)

234
