#### Create a NumPy array of integers from 1 to 12 and reshape it into a 3×4 matrix.

In [1]:
import numpy as np


In [3]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [6]:
arr1=np.arange(1,13).reshape(4,3)
print(arr1)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


#### Compute the mean, median, and standard deviation of a random array of size 10 drawn from a uniform distribution between 0 and 1.

In [7]:
speed=np.random.rand(10)
print(speed)

[0.97660842 0.87933023 0.25440313 0.66284567 0.7105592  0.64834225
 0.63970595 0.31120067 0.76407917 0.94768282]


In [8]:
print(f"Mean:{np.mean(speed)}")

Mean:0.6794757518683696


In [9]:
print(f"Median:{np.median(speed)}")

Median:0.6867024381122083


In [10]:
print(f"Std_Deviation:{np.std(speed)}")

Std_Deviation:0.22965829901517326


In [95]:
print(f"Sum:{np.sum(speed)}")

Sum:6.794757518683696


In [97]:
print(f"Maximum:{np.max(speed)}")

Maximum:0.9766084180075655


In [98]:
print(f"Minimum:{np.min(speed)}")

Minimum:0.25440313393890646


In [100]:
np.min?

Signature:      
np.min(
    a,
    axis=None,
    out=None,
    keepdims=<no value>,
    initial=<no value>,
    where=<no value>,
)
Call signature:  np.min(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function min at 0x0000021FB33D7F60>
File:            c:\users\user 10\anaconda3\lib\site-packages\numpy\_core\fromnumeric.py
Docstring:      
Return the minimum of an array or minimum along an axis.

Parameters
----------
a : array_like
    Input data.
axis : None or int or tuple of ints, optional
    Axis or axes along which to operate.  By default, flattened input is
    used.

    .. versionadded:: 1.7.0

    If this is a tuple of ints, the minimum is selected over multiple axes,
    instead of a single axis or all the axes as before.
out : ndarray, optional
    Alternative output array in which to place the result.  Must
    be of the same shape and buffer length as the expected output.
    See :ref:`ufuncs-output-type` for more details.

keepdims : b

In [99]:
np.max?

Signature:      
np.max(
    a,
    axis=None,
    out=None,
    keepdims=<no value>,
    initial=<no value>,
    where=<no value>,
)
Call signature:  np.max(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function max at 0x0000021FB33D7E20>
File:            c:\users\user 10\anaconda3\lib\site-packages\numpy\_core\fromnumeric.py
Docstring:      
Return the maximum of an array or maximum along an axis.

Parameters
----------
a : array_like
    Input data.
axis : None or int or tuple of ints, optional
    Axis or axes along which to operate.  By default, flattened input is
    used.

    .. versionadded:: 1.7.0

    If this is a tuple of ints, the maximum is selected over multiple axes,
    instead of a single axis or all the axes as before.
out : ndarray, optional
    Alternative output array in which to place the result.  Must
    be of the same shape and buffer length as the expected output.
    See :ref:`ufuncs-output-type` for more details.

keepdims : b

In [96]:
np.sum?

Signature:      
np.sum(
    a,
    axis=None,
    dtype=None,
    out=None,
    keepdims=<no value>,
    initial=<no value>,
    where=<no value>,
)
Call signature:  np.sum(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function sum at 0x0000021FB33D7420>
File:            c:\users\user 10\anaconda3\lib\site-packages\numpy\_core\fromnumeric.py
Docstring:      
Sum of array elements over a given axis.

Parameters
----------
a : array_like
    Elements to sum.
axis : None or int or tuple of ints, optional
    Axis or axes along which a sum is performed.  The default,
    axis=None, will sum all of the elements of the input array.  If
    axis is negative it counts from the last to the first axis.

    .. versionadded:: 1.7.0

    If axis is a tuple of ints, a sum is performed on all of the axes
    specified in the tuple instead of a single axis or all the axes as
    before.
dtype : dtype, optional
    The type of the returned array and of the accumulator i

In [11]:
np.mean?

Signature:      
np.mean(
    a,
    axis=None,
    dtype=None,
    out=None,
    keepdims=<no value>,
    *,
    where=<no value>,
)
Call signature:  np.mean(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function mean at 0x0000021FB33E8860>
File:            c:\users\user 10\anaconda3\lib\site-packages\numpy\_core\fromnumeric.py
Docstring:      
Compute the arithmetic mean along the specified axis.

Returns the average of the array elements.  The average is taken over
the flattened array by default, otherwise over the specified axis.
`float64` intermediate and return values are used for integer inputs.

Parameters
----------
a : array_like
    Array containing numbers whose mean is desired. If `a` is not an
    array, a conversion is attempted.
axis : None or int or tuple of ints, optional
    Axis or axes along which the means are computed. The default is to
    compute the mean of the flattened array.

    .. versionadded:: 1.7.0

    If this is a tuple

In [12]:
np.median?

Signature:       np.median(a, axis=None, out=None, overwrite_input=False, keepdims=False)
Call signature:  np.median(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function median at 0x0000021FB353BE20>
File:            c:\users\user 10\anaconda3\lib\site-packages\numpy\lib\_function_base_impl.py
Docstring:      
Compute the median along the specified axis.

Returns the median of the array elements.

Parameters
----------
a : array_like
    Input array or object that can be converted to an array.
axis : {int, sequence of int, None}, optional
    Axis or axes along which the medians are computed. The default,
    axis=None, will compute the median along a flattened version of
    the array.
    
    .. versionadded:: 1.9.0

    If a sequence of axes, the array is first flattened along the
    given axes, then the median is computed along the resulting
    flattened axis.
out : ndarray, optional
    Alternative output array in which to place the result. It m

In [14]:
np.std?

Signature:      
np.std(
    a,
    axis=None,
    dtype=None,
    out=None,
    ddof=0,
    keepdims=<no value>,
    *,
    where=<no value>,
    mean=<no value>,
    correction=<no value>,
)
Call signature:  np.std(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function std at 0x0000021FB33E89A0>
File:            c:\users\user 10\anaconda3\lib\site-packages\numpy\_core\fromnumeric.py
Docstring:      
Compute the standard deviation along the specified axis.

Returns the standard deviation, a measure of the spread of a distribution,
of the array elements. The standard deviation is computed for the
flattened array by default, otherwise over the specified axis.

Parameters
----------
a : array_like
    Calculate the standard deviation of these values.
axis : None or int or tuple of ints, optional
    Axis or axes along which the standard deviation is computed. The
    default is to compute the standard deviation of the flattened array.

    .. versionadded::

#### Given two NumPy arrays a = [1,2,3,4] and b = [2,2,10,4], find the element-wise comparison(equal, greater, less).

In [23]:
arr1=np.array([1,2,3,4])
arr2=np.array([2,2,10,4])

In [17]:
print(f"Equal:{np.equal(arr1,arr2)}")

Equal:[False  True False  True]


In [18]:
print(f"Greater:{np.greater(arr1,arr2)}")

Greater:[False False False False]


In [19]:
print(f"Less:{np.less(arr1,arr2)}")

Less:[ True False  True False]


In [21]:
arr1 = np.array([[1, 2, 3],[4, 5, 6]])

In [22]:
np.transpose(arr1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [24]:
print("Vertical Stack:\n", np.vstack((arr1, arr2)))
print("Horizontal Stack:\n", np.hstack((arr1, arr2)))

Vertical Stack:
 [[ 1  2  3  4]
 [ 2  2 10  4]]
Horizontal Stack:
 [ 1  2  3  4  2  2 10  4]


#### Create a 5×5 matrix where each element is the sum of its row and column indices.

In [41]:
col=np.arange(5).reshape(5,1)

In [42]:
print(col)

[[0]
 [1]
 [2]
 [3]
 [4]]


In [43]:
row=np.arange(5)

In [44]:
print(row)

[0 1 2 3 4]


In [45]:
Sum=row + col

In [46]:
print(Sum)

[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]]


#### Create a Pandas DataFrame from a dictionary containing columns 'Name', 'Age', and 'City'.

In [47]:
import pandas as pd

In [70]:
data = {'Name': ['Asha', 'Ravi', 'Seema'],
'Age': [25, 30, 28],
'City': ['Bangalore', 'Chennai', 'Pune']}

In [71]:
print(data["Name"])

['Asha', 'Ravi', 'Seema']


In [72]:
print(data["City"])

['Bangalore', 'Chennai', 'Pune']


In [73]:
data["City"]=['Bangalore', 'Chennai', 'Pune']
print(data["City"])

['Bangalore', 'Chennai', 'Pune']


In [74]:
for city in data["City"]:
    print(city)

Bangalore
Chennai
Pune


In [63]:
(data["City"].append("Kolkata"))

In [64]:
print(data["City"])

['Bangalore', 'Chennai', 'Pune', 'Kolkata']


In [75]:
print(pd.DataFrame(data))

    Name  Age       City
0   Asha   25  Bangalore
1   Ravi   30    Chennai
2  Seema   28       Pune


#### Filter rows from a DataFrame where Age are greater than 50

In [78]:
df=pd.DataFrame(data)

In [79]:
print(df)

    Name  Age       City
0   Asha   25  Bangalore
1   Ravi   30    Chennai
2  Seema   28       Pune


In [84]:
Filtered_df=df[(df['Age'] > 26)]

In [85]:
Filtered_df

Name  Age     City
1   Ravi   30  Chennai
2  Seema   28     Pune

#### Given a DataFrame with columns ['Region', 'Sales', 'Profit'], compute total sales and average profit by region.

In [88]:
Sales_data = {
'Region': ['North', 'South', 'North', 'East', 'South'],
'Sales': [5000, 7000, 6000, 4500, 8000],
'Profit': [500, 700, 600, 450, 800]}

In [89]:
Sales_df=pd.DataFrame(Sales_data)

In [91]:
Sales_df

Region  Sales  Profit
0  North   5000     500
1  South   7000     700
2  North   6000     600
3   East   4500     450
4  South   8000     800

## SQL query connected with dataframe as pandas

In [92]:
# select Region,sum(Sales),avg(Profit) from Sales_df group by Region

In [93]:
summary = Sales_df.groupby('Region').agg({'Sales': 'sum', 'Profit': 'mean'})

In [94]:
summary

Sales  Profit
Region               
East     4500   450.0
North   11000   550.0
South   15000   750.0